### ISSUE TITLE
Section admin show page & page search

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#1014]
Mockup template: http://gobierto.dev/sandbox/admin_cms_sections_section

Implement:

### Edit / update the section

- When clicking in **Configuration** a form will open to update the current section title or slug.
- After saving the section, the user will be redirected to this page.
- Track update activities.

### Search pages

Implement a live search of the current site pages.

**Comment by apradillap** [comment]
Deployed:
- Staging + reindex
- Dival + reindex
- Production + reindex
