### ISSUE TITLE
Admin links to frontend for attachments without collection

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto#1031]
When creating/updating and attachment from the admin UI, we get the typical *"success link"* to view the resource:

![update-success-link](https://user-images.githubusercontent.com/9287468/31778954-4615bfd6-b4f2-11e7-9597-db142974ee74.png)

But as we see in this routes, we now only have the capability to view attachments in the frontend when they have a collection like a process or issue:

![rutas-attachments](https://user-images.githubusercontent.com/9287468/31778957-479f115e-b4f2-11e7-920c-7dda36682f33.png)

So when the link is retrieved for attachments which are not linked to a collection, an empty `href` attribute will be rendered:

```ruby
# attachment.rb => to_url()
def to_url(options = {})
  if collection
     if collection.container_type == "GobiertoParticipation::Process"
      # etc.
    elsif collection.container_type == "GobiertoParticipation"
      # etc.
    end
  end
end
```

And the link will lead to `'#'`. We should provide a way to see this attachments.

**Comment by ferblape** [comment]
Fixed
