### ISSUE TITLE
Use FileAttachmentForm in the attachments API

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto#1032]
When I did the `Attachment` model and its admin API, `::GobiertoAdmin::GobiertoAttachments::FileAttachmentForm` didn't exist yet, so I added a series of methods/validations to `attachment.rb` which are now duplicated in the form object. We should delete this methods and make the admin API to also use the form object.

The code which is duplicated is:

* `update_file_attributes` and `unique_file_digest?` methods in `attachment.rb`
* The `file_digest` uniqueness validation in `attachment.rb`

**Comment by ferblape** [comment]
In production there are lots of attachments without the collection_id set. This issue is the root cause.

Rollbar that arrived yesterday:  https://rollbar.com/Populate/gobierto/items/1308/?item_page=0&item_count=100&#traceback
