### ISSUE TITLE
Add a bit of context in the collection

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#1061]
Minor.

Add the context and the type in the list of collections. Something like:

![screen shot 2017-11-01 at 11 42 43](https://user-images.githubusercontent.com/17616/32271376-dc2c96fa-bef9-11e7-94a9-c0e19531a44c.png)

This way we avoid the confusion of duplicated names.

**Comment by furilo** [comment]
This is already reflected in the sandbox: 

http://madrid.gobierto.dev/sandbox/admin_agendas
http://madrid.gobierto.dev/sandbox/admin_cms

When listing a collection, we should show: 

* Module/Resource/Collection_Title (pages|news)

Examples: 

* News section of a process: Participacion/Participación/Proceso con Título que Puede llegar a ser muy largo/Noticias (noticias)
* News of a module: Presupuestos/Historias (noticias)
* Help section of the site: Site/Acerca de (páginas)
