### ISSUE TITLE
Extract User-specific logic from ApplicationController

### ISSUE THREAD

**Issue by danguita** [PopulateTools/gobierto#108]
As seen today in the Staging environment, some User namespace-specific logic is defined at `ApplicationController` level so any other controllers are inheriting them.

In example, the `authenticate_user_in_site` callback should not be triggered in other namespaces but the User one.

Let's just write it down for a possible refactor.

**Comment by ferblape** [comment]
Picking this one, which is getting a bit annoying in staging.
