### ISSUE TITLE
Tests that usually fail in CI

### ISSUE THREAD

**Issue by apradillap** [PopulateTools/gobierto#1099]
- [ ] test/integration/gobierto_participation/processes/process_contribution_containers_show_test.rb
- [ ] test/integration/gobierto_participation/processes/process_pages_index_test.rb
- [ ] test/integration/gobierto_people/people/person_event_show_test.rb
- [ ] test/integration/gobierto_participation/processes/process_events_show_test.rb
- [ ] test/integration/gobierto_budget_consultations/consultation_show_test.rb
- [ ] test/integration/user/subscription_index_test.rb
- [ ] test/integration/gobierto_budget_consultations/consultation_response_create_test.rb
- [ ] test/integration/gobierto_people/person_profile_test.rb
- [ ] test/integration/gobierto_participation/processes/poll_answers/poll_answers_create_test.rb
- [ ] test/integration/gobierto_participation/processes/process_show_test.rb
- [ ] test/integration/gobierto_participation/processes/process_pages_show_test.rb

**Comment by ferblape** [comment]
Fixed in #1005
