### ISSUE TITLE
Shorten long attributes for Algolia

### ISSUE THREAD

**Issue by apradillap** [PopulateTools/gobierto#1117]
These days when we have been putting content in the pages for one client, we have observed that we send to Algolia to index has "big size" when the pages have a lot of content for our "Algolia quote":
```
{
  "message": "Record at the position 15 objectID=21 is too big size=20072 bytes. Contact us if you need an extended quota",
  "position": 15,
  "objectID": "21",
  "status": 400
}
```

These models and their attributes (some are multi-language) are affected:

Attachment:
- description

Event:
- description

Person:
- description

Contribution:
- description

Process:
- body

PersonPost:
- body

Page:
- body

**Comment by apradillap** [comment]
@ferblape Initially we thought to reduce that we send to Algolia but it won't search all the content of the page. Is The solution to increase Algolia's quota?

**Comment by ferblape** [comment]
I've just asked Algolia to increase our record limits.
