### ISSUE TITLE
Archive elements as a way to soft-delete

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#1128]
I propose that we implement an archive function that would serve as a soft-delete. 

- In the front: Archived elements would behave as deleted elements. That is, they should not appear in any public place.
- In the admin: we would create a new classification for Archived elements. If you archive an element, it would go to this page; you would be able to recover (un-archive) an element and it would come back to normal.

This is an inventory of entities I would implement this for: 

## General

- [x] Pages
- [x] Events
- [x] Documents

## Participation

- [x] Processes
  - [x] Polls
  - [x] ContributionContainers

Please @apradillap give it a thought of what more elements we should take into account.

---

For the front-end, let's do the following: 

- in list tables, add a column at the end of the table, where we put the icon trash, with class "tipsit ", and title: "Archive this element"
- when clicking on trash, we show this JS alert: "Are you sure you want to archive this element? It won't show on the front end neither on lists like this. You will be able to recover it"
- After the table, if archived elements exist, add: 
```
<div class="m_v_1 right">
<a href="">Archived elements</a>
</div>
```
- when clicking on "archived elements", show a table with the same columns but without linking the elements, except for the first one (edit icon), and a last column that reads "Recover element", with class "tipsit" and title: "If you recover an element, it will be listed again"

**Comment by apradillap** [comment]
For logical deletion I used https://github.com/rubysherpas/paranoia

**Comment by furilo** [comment]
issue updated

**Comment by furilo** [comment]
Do we have the soft delete for processes inside Participation? I can't see it in /admin/participation

**Comment by apradillap** [comment]
Not for processes @furilo , I'll add it
