### ISSUE TITLE
Include option in Budgets to show comparison widgets, linking to presupuestos.gobierto.es

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#1131]
Define where and what to include it. Initial ideas: 

- Besides the context graphs
- As a full width promo in the home/pre-footer?
- As an option in the main menu?

---

Tasks: 

- [x] Design
- [x] HTML
- [ ] Implementation
  - Option in admin
  - Front

**Comment by furilo** [comment]
## Design proposal 

![imagen](https://user-images.githubusercontent.com/24740/33244890-b1bd3522-d2ff-11e7-97ac-0eecf0fe92c8.png)

We'd have to choose one of the options. Which looks best?

## Conf options

This is the conf (and corresponding behaviour) that we'd have in the admin. This means that we make flexible to choose which modules we show in the context area: the current one, a series of places defined per site, and the comparison widget that would take you to presupuestos.gobierto.es

- CHECK Comparación
  Habilita herramientas de comparación 

  - SUBCHECK Mostrar tabla de Contexto
    Muestra la tabla que ofrece contexto con medias provinciales, autonómicas o estatales

  - SUBCHECK Mostrar municipios específicos
    Muestra una tabla con municipios específicos (y cuyos datos estén disponibles en presupuestos.gobierto.es - haz la comprobación allí antes de incluirlos)
    [INPUT]
    Selecciona los municipios

  - SUBCHECK Mostrar widget comparación
    Facilita el acceso a la herramienta de comparación de presupuestos de Gobierto: presupuestos.gobierto.es

@ferblape take a look. Once we have the design choosen, it can be integrated together with the options.

**Comment by ferblape** [comment]
LGTM. I like the third design option.

**Comment by furilo** [comment]
OK! @Crashillo can you add this in the view? The image is already in the repo.
