### ISSUE TITLE
Improve emplyoment graphs

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#1134]
<img width="1266" alt="imagen" src="https://user-images.githubusercontent.com/24740/32946169-c0b21b12-cb96-11e7-9175-1e76a3eacb36.png">

I'd say: 

- make them shorter. we can try with 250px height instead of current one
- fix the scale, so graph line don't go below the bottom axe
- add more tick lines, so they give closure to the graph?

**Comment by ferblape** [comment]
@furilo please review in staging:

![screen shot 2017-11-20 at 16 23 59](https://user-images.githubusercontent.com/17616/33025842-4e0db532-ce0f-11e7-915c-1b0dd3cdec30.png)

I've done everything except adding more tick lines because doesn't seem necessary now with the reduction of the height.
