### ISSUE TITLE
Allow select a page as the home of a site

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#1150]
Following #1062 we should enable that an admin can select a page or a section as the home of a site. For Getafe we need a page, but can do two things now: 

- Add a new option in the Start Page select: GobiertoCMS
- If GobiertoCMS is selected, show a second select, with the list of sections and then the list of pages
  - when we have tons of pages, we may implement something like this https://select2.org/dropdown to make it easier to select an specific page

Example of select: 

```
Section A
Section B
Section C
---
Pages (non-selectable option)
Page A
Page B
Page C
...
```

**Comment by apradillap** [comment]
Seen, I think what you're proposing is a very good solution. 👍
