### ISSUE TITLE
Suggest budgets items when typing

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#118]
In the consultation item page, we are shoing a lot of budget items to the user, and it's a bit complex to pick a specific budget line.

Change the behaviour and implement a typeahead (auto-suggest) that suggest budgets while the user is typing.

**Comment by danguita** [comment]
I was handling that in https://github.com/PopulateTools/gobierto-dev/issues/92. Let's keep this Issue open for a better control over changes 👍

**Comment by danguita** [comment]
@ferblape Let me close this one in favor of https://github.com/PopulateTools/gobierto-dev/issues/92.
