### ISSUE TITLE
Budget line amounts

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#119]
In the consultation item page, when a budget line is selected we should simplify the amounts displayed:

- [x] add the unit
- [x] round the thousands (i.e: 124.000€ instead of 123.567€)
- [x] avoid milions (i.e. 123M€; 1,24M€; 123.000€)

**Comment by danguita** [comment]
This one depends on https://github.com/PopulateTools/gobierto-dev/pull/130. Let's keep in back-log for now.

**Comment by danguita** [comment]
Nevermind, we can move it forward.
