### ISSUE TITLE
Budgets / Invoices-Providers section

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#1191]
Design in Sketch

- [x] Markup
- [ ] Implementation

**Comment by ferblape** [comment]
Basic data format to be exported in the CSV:

- nif: string
- name: string
- date: format YYYY/MM/DD
- paid: boolean
- amount: float
- concept: string
- freelance: boolean

**Comment by ferblape** [comment]
New format (v2):

Basic data format to be exported in the CSV:

- invoice_id: uuid string
- provider_id: string
- provider_name: string
- date: format YYYY/MM/DD
- payment_date: format YYYY/MM/DD
- paid: boolean
- amount: float
- subject: string
- freelance: boolean
- economic_budget_line_code: string
- functional_budget_line_code: string
