### ISSUE TITLE
Basic test suite for GobiertoBudgets module

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#12]
GobiertoBudgets module doesn't have any test right now that checks if the module is working.

Create a minimum test suite to cover at least:

- [x] home page
  - [x] home page boxes
  - [x] home page main budget lines block
  - [x] home page highlighted budget lines
- [x] budget lines page
- [x] budget line page
- [x] execution page

**Comment by danguita** [comment]
❤️
