### ISSUE TITLE
Improve mobile menu

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#1217]
@Crashillo Sketch file shared in Dropbox (look at the page "To HTML")

Marvel reference: https://marvelapp.com/12047afg/

**Comment by ferblape** [comment]
Nop, I like the version with the dropdown instead of the menu items in horizontal:

![screen shot 2017-12-04 at 17 34 56](https://user-images.githubusercontent.com/17616/33563926-811d6da4-d919-11e7-8fc5-1a7d66a6407b.png)

**Comment by furilo** [comment]
is this integrated? can we put it in staging for review?

**Comment by Crashillo** [comment]
Nope. It's still missing to add some rails dynamic contents (like the current module/submodule names). Right now, that's static.

**Comment by furilo** [comment]
Please review in newalcobendas. There are some things pending to sort out...

**Comment by furilo** [comment]
Issues I see (in Safari): 

- If you are in a section (http://newalcobendas.gobify.net/participacion/ambitos): 
  - you are not shown the title of the section: 
![new alcobendas de new alcobendas participacion gobierto 2018-02-05 09-17-09](https://user-images.githubusercontent.com/24740/35794276-6d7e616e-0a55-11e8-8223-253f4d6f44aa.png)
  - If you open the main menu, secondary links are not shown:   
![captura de pantalla 2018-02-05 a las 9 19 06](https://user-images.githubusercontent.com/24740/35794331-a2afa866-0a55-11e8-9ca9-b02e3a4590a5.png)
- When you are inside a module and open the main menu, that section in the menu should be opened. So, if you are in Participation, the Participation section in the menu should be opened, like: 
![captura de pantalla 2018-02-05 a las 9 20 51](https://user-images.githubusercontent.com/24740/35794437-ff6dcea2-0a55-11e8-9899-dfc9fffab48a.png)
- Can we bottom-align the global header links and the secondary links? As in https://marvelapp.com/12047afg/screen/36491217: 
![captura de pantalla 2018-02-05 a las 9 22 25](https://user-images.githubusercontent.com/24740/35794459-1a07a922-0a56-11e8-96e9-5daa1ced39de.png)

**Comment by ferblape** [comment]
All issues solved except the last one to align the menu to the bottom. I'll let you solve that @Crashillo
