### ISSUE TITLE
Verification link when you are verified

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#125]
If you login with Dennis, a verified user, you'll see a link "Verify your account" although you are verified.

**Comment by danguita** [comment]
Yup, that is intended until we decide what to do with the session toolbar. Agree on just hiding it when the signed in User is verified against census for the current site 👍

**Comment by danguita** [comment]
Picking this one.

**Comment by danguita** [comment]
That link has been removed in https://github.com/PopulateTools/gobierto-dev/pull/102, so I'm closing this one in the meantime.
