### ISSUE TITLE
Observatory / Help icon doesn't flip the card

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#1259]
Previously the help icon on a card fliped it so the souce was shown. This stopped working

![imagen](https://user-images.githubusercontent.com/24740/33928882-b8b77a8c-dfe7-11e7-9a9b-547280322a6f.png)

**Comment by ferblape** [comment]
I'm assigning you @Crashillo because it's all implemented in CSS and I can't understand why is not working.
