### ISSUE TITLE
Allow admin to visit front as a normal user

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#127]
__To be discussed__

As an admin, it's a common scenario to visit the user namespace to check how a consultation looks like, or even to test it. It'll happen in the future with other modules.

We should find a way to allow a logged admin to be authorized in the front part as a user without limitations (verified?).

**Comment by ferblape** [comment]
Let's discuss it tomorrow morning.

**Comment by furilo** [comment]
For the moment, just take into account: 

- admin creates item in draft mode, the system provides the URL for previewing it with some hash to allow access

**Comment by ferblape** [comment]
This has been address in #716
