### ISSUE TITLE
Rename Gobierto Indicators -> Observatory

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#1270]
Indicators in the world of transparency is many times used for official ranking of indicators. Therefore, our current Gobierto Indicators module is a bit misleading. Given that we are starting a module to show those rankings, we are going to rename the current Gobierto Indicators to Observatory. 

User facing: I guess only in the menu, locales... 

Dev facing: 

- rename module (namespace) to `GobiertoObservatory`:
  - javascripts folder
  - routes
  - controller
  - views
  - fixtures
- update application.yml (Ansible)
- data migration to update sites settings

When we deploy the change, we should probably rename the current "Gobierto Indicators" Github tag to "Gobierto Observatory", and create a new "Gobierto Indicators"

Anything else to take into account?

**Comment by ferblape** [comment]
Issue updated
