### ISSUE TITLE
Scope users in sites

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#1312]
User model was designed to be available in all sites, and using the field `source_site_id` we know the first site where she signed up.

We are going to change this approach and link users to sites. Therefore we need:

- add a `site_id` field, using the value from `source_site_id`
- remove `source_site_id` field
- scope the validations to the `site_id`, so we could have multiple users with the same email in different sites
- user this scope in the Session / Signup controllers
- update Form objects
- update tests and fixtures, taking care of the users in the current site
- update docs/user-namespace.md
- amend admin users list to fetch only the users in that site

**Comment by entantoencuanto** [comment]
Deployed in staging. The part of confirmation token and password recover must be reviewed, it seems that there are some cross-site errors calling to a site with the token of another.
