### ISSUE TITLE
Invoices / Improvements to filtering and table

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#1315]
- [x] When filtering the DC, let's update the table
- [x] When filtering the table, let's update the DC
- [x] Table: check if the library has an option out of the box to allow users to customize the number of items per page 
- [x] Table: if you enter a date (ie. "1/1/2017") no results are returned. Maybe the "/" is not correctly scaped?
- [x] Spinner while loading

**Comment by Crashillo** [comment]
> Table: check if the library has an option out of the box to allow users to customize the number of items per page

Regarding this I've seen there is an option to set the pageSize on render, but to allow users set it up, it requires to add a select markup outside of the table. jsGrid does not include that functionality beyond this.

**Comment by furilo** [comment]
> Regarding this I've seen there is an option to set the pageSize on render, but to allow users set it up, it requires to add a select markup outside of the table. jsGrid does not include that functionality beyond this.

OK, for the moment just make 50 as the default number of elements per page

**Comment by Crashillo** [comment]
OK. It's all done in #1285
