### ISSUE TITLE
Implement a Budget line data endpoint in Gobierto's side

### ISSUE THREAD

**Issue by danguita** [PopulateTools/gobierto#132]
This is a follow up to https://github.com/PopulateTools/gobierto-dev/issues/92.

Just for the record, we should consider implementing an enhancement regarding the current Budget line retrieval and aggregation behavior. It may consist on implementing an endpoint in Gobierto's side to let the autocomplete control request a remote data source instead of doing it inline in rendering time as we do right now. That endpoint may be in charge of caching and expiring the aggregated data.

**Comment by ferblape** [comment]
👍
