### ISSUE TITLE
Error detecting existing elements already archived

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#1340]
This is an issue in `GobiertoCalendars::Event` but potentially can affect to all the classes that support soft-delete.

Before creating and event, the process checks in the database if the event exists with this query:

```sql
SELECT  1 AS one FROM "gc_events" WHERE "gc_events"."archived_at" IS NULL AND "gc_events"."site_id" = 9 AND "gc_events"."slug" = $1 LIMIT $2  [["slug", "2018-01-15-despatx-amb-el-primer-tinent-d-alcaldia"], ["LIMIT", 1]]
```

Notice the `archived_at IS NULL` statement. If there's an element archived this query won't detect it, and the INSERT query will fail 💥:

```sql
INSERT INTO "gc_events" ("starts_at", "ends_at", "state", "created_at", "updated_at", "title_translations", "description_translations", "external_id", "site_id", "slug", "collection_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING "id"  [["starts_at", "2018-01-15 11:00:00"], ["ends_at", "2018-01-15 12:00:00"], ["state", 1], ["created_at", "2018-01-16 14:26:31.360783"], ["updated_at", "2018-01-16 14:26:31.360783"], ["title_translations", "{\"es\":\"@ Despatx amb el primer tinent d'alcaldia\"}"], ["description_translations", "{\"es\":null}"], ["external_id", "F4DEE6203892A72DC125821200401D31-Lotus_Notes_Generated"], ["site_id", 9], ["slug", "2018-01-15-despatx-amb-el-primer-tinent-d-alcaldia"], ["collection_id", 168]]
```

Rollbar: https://rollbar.com/Populate/gobierto/items/725/

**Comment by apradillap** [comment]
@ferblape , Would the solution be to validate at this point if that event already exists in the database if it is archived?

https://github.com/PopulateTools/gobierto/blob/master/app/forms/gobierto_people/person_event_form.rb#L170

**Comment by ferblape** [comment]
I'm thinking on removing the slug when the item is archived, and re-calculating it when the item is re-published. We could add this logic to the concern you created.

Does the gem provides callbacks to do this?
