### ISSUE TITLE
New API for retrieving elements belonging to a collection

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto#1354]
As seen [here](https://github.com/PopulateTools/gobierto/blob/cf628a75730df8b145c60cb5a04b3c619ece7fb4/app/models/gobierto_cms/page.rb#L70-L101) the API for retrieving pages etc. from a collection is has become a bit confusing, we should find a clearer way of performing these operations. ¿Maybe took a a look at [this](https://github.com/PopulateTools/gobierto/blob/cf628a75730df8b145c60cb5a04b3c619ece7fb4/app/models/gobierto_common/collection.rb#L33-L51) also?

**Comment by furilo** [comment]
What's pending here?

**Comment by amiedes** [comment]
Answer [here](https://github.com/PopulateTools/gobierto/pull/1440)
