### ISSUE TITLE
Control contributions instance dates to allow participation

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#1405]
Right now it seems you can create a contribution even if the contributions instance date is configured to start in the future.

**Comment by amiedes** [comment]
When the contributions period has finished I'm gonna do this with the button and the comments but let users view the pool to explore the content:

![captura de pantalla 2018-02-08 a las 17 39 31](https://user-images.githubusercontent.com/9287468/35985484-0a76e330-0cf7-11e8-8674-10c247ab587d.png)

¿What should I do when the period starts in the future? ¿Disable also the button (and the user will see an empty pool) or maybe *gray-out* the link to the corresponding pool?

![captura de pantalla 2018-02-08 a las 17 40 26](https://user-images.githubusercontent.com/9287468/35985544-2ed9ebf0-0cf7-11e8-9a9b-2479b7c1ee9d.png)

**Comment by furilo** [comment]
Inside the pool: OK


In the listing of pools, leave the description, and add:

<p>El periodo de aportaciones ha finalizado</p>
<p>El periodo de aportaciones comenzará el 12 dic 2018</p>

Update the texts inside the pool acordingly

OJO, we are not calling publicly this spaces "pools", thats something
internal, so it should not be used in the public (nor private) UI

**Comment by amiedes** [comment]
A few more doubts. When the contributions period has finished, should we allow:

* Commenting when the contributions period has already finished? (I think no)
* Voting (+1/-1) a comment or reporting it? (I think yes)
* Voting a contribution? (I think no)

Right now all of this is allowed

**Comment by furilo** [comment]
We don't allow nothing if the contributions space is closed
