### ISSUE TITLE
Cual es el branch?

### ISSUE THREAD

**Issue by cesarandreslp** [PopulateTools/gobierto#1425]
Buenas tardes les escribo desde el municipio de Guadalajara de Buga en Colombia y junto con unos compañeros de trabajo hemos tratado de poner a correr la plata forma de Gobierto siguiendo los pasos que se Indican en el archivo INSTALL.MD y al llegar al punto 2 y tratar de ubicar el archivo production.yml nos dimos cuenta de que no está en la ruta config/settings/production.yml
Del branch master.
La pregunta es: ¿cual es el branch que se encuentra en producción y que debemos usar para desplegar la plaforma? 

De antemano muchas gracias por su colaboración y respuesta.

Atentamente;

César Andres Lozano

**Comment by ferblape** [comment]
Hola César, Acabamos de actualizar el INSTALL.md porque estaba obsoleto. El branch estable y el que usamos en producción es `master.

Hay que utilizar un fichero de variables de entorno. Si se usa Rbenv, el fichero se tiene que llamar `.rbenv-vars` . Todas las variables de entorno que pueden hacer falta están documentadas aquí: https://github.com/PopulateTools/gobierto/blob/master/docs/environment-variables.md

**Comment by cesarandreslp** [comment]
Muchas Gracias por la pronta respuesta
