### ISSUE TITLE
Run calendar sync in the site default locale

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#1451]
Now, the calendar sync executed by an Admin runs in the admin locale. It makes the events information (title and description) is imported in the locale of the admin.

It'd be more appropiate to import the data in the site default locale.

Even more, when assigning the attributes in the `PersonEventForm` object, we should be explicit about the locale of the attribute. Should be:

```ruby
person_event_attributes.title_translations = { ca: title, es: nil, en: nil }
person_event_attributes.description_translations = { ca: description, es: nil, en: nil }
```

Instead of:

```ruby
person_event_attributes.title = title
person_event_attributes.description = description
```

**Comment by furilo** [comment]
Really, we should apply the text filter to all locales, as now it's only
being applied to one?

**Comment by ferblape** [comment]
That's another issue: https://github.com/PopulateTools/gobierto/issues/1452
