### ISSUE TITLE
Errors in counters

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#1468]
This counters should be counting only items in the corresponding categories, but they are counting total items in the plan. 

![captura de pantalla 2018-02-20 a las 14 39 43](https://user-images.githubusercontent.com/24740/36426911-eb35a7be-164b-11e8-97f4-bbe541ef5a87.png)
![captura de pantalla 2018-02-20 a las 14 39 48](https://user-images.githubusercontent.com/24740/36426913-eb5017a2-164b-11e8-857d-cf2cd4ae8303.png)

**Comment by Crashillo** [comment]
cc/ @apradillap 

I've seen calculation is made in https://github.com/PopulateTools/gobierto/blob/2643ff88984ebabae920fdae160a44e6bf6d13e9/app/views/gobierto_plans/plans/show.html.erb#L96

**Comment by ferblape** [comment]
This is still happenning in staging and production.
