### ISSUE TITLE
Update Magnific Popup library to its latest version

### ISSUE THREAD

**Issue by danguita** [PopulateTools/gobierto#149]
It seems this library is still having some incompatibilities with Safari 8 and 9 versions. Let's upgrade it to [1.1.0](https://github.com/dimsemenov/Magnific-Popup/releases/tag/1.1.0) to investigate them from a clean state.

Just for the record, the error is:

```
Syntax error: - Invalid character '\u0215'
```

@furilo Thanks for reporting!

**Comment by ferblape** [comment]
Picking this one.
