### ISSUE TITLE
Budgets / Indicators page

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#1510]
- New subsection in Budgets module. A simple page that shows a grid with cards as in /observatorio
- In the submenu, at the end: "Indicadores"
- The indicators: the ones we have already calculated: https://github.com/PopulateTools/populate-data-indicators/tree/master/i-presupuestos-municipales/datasets

ds-ahorro-bruto 	
ds-ahorro-neto 	
ds-autonomia-fiscal 	
ds-capacidad-autofinanciacion 	
ds-carga-financiera 	
ds-coste-deuda 	
ds-financiacion-inversiones 	
ds-indice-ahorro-bruto 	
ds-indice-ahorro-neto 	
ds-inversion-por-habitante
ds-nivel-endeudamiento 	
ds-presion-fiscal-por-habitante 	
ds-presupuestos-municipales-partida
ds-presupuestos-municipales-total
ds-riesgo-financiero
ds-rigidez-gasto 	

- We'll use the basic card (the first one you can see in https://portalobert.esplugues.cat/observatorio): 
  ![imagen](https://user-images.githubusercontent.com/24740/37274762-b54f71b0-25dd-11e8-8f74-6819d24597d4.png)

Related: https://github.com/PopulateTools/issues/issues/267

**Comment by ferblape** [comment]
@apradillap, these should be the steps:

- controller, action and a route inside budgets module
- same template as the observatory page, where the Rails template is just the container and the content is mostly javascript, but changing the literals
- in the view, check how the observatory is done, basically use the card template and fill all the cards with calls to all those indicators described in the issue in Javascript. You can copy the code from the observatory module
- an admin option to enable / disable the indicators

If you get stuck with the Javascript ask @Crashillo or me 🤖

**Comment by furilo** [comment]
Sorry - data is from different years. If you check data for 2015, Ahorro bruto mostly checks, but not neto: 

![imagen](https://user-images.githubusercontent.com/24740/37414725-14386af6-27aa-11e8-8c27-8abb87d3b7d7.png)

**Comment by furilo** [comment]
In http://getafe.gobify.net/presupuestos/indicadores/2017 I see two empty indicators at the bottom

![imagen](https://user-images.githubusercontent.com/24740/37645219-7f3d4044-2c26-11e8-933d-986121b220a5.png)

**Comment by apradillap** [comment]
Corrected the blank indicators. When you changed the year, it doubled the line, but now it's fixed.
