### ISSUE TITLE
Review and confirm content of emails and translate them

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#154]
Emails views are these ones:

- https://github.com/PopulateTools/gobierto-dev/tree/master/app/views/gobierto_admin/admin_mailer
- https://github.com/PopulateTools/gobierto-dev/tree/master/app/views/user/user_mailer

@furilo please confirm the texts are ok or propose amends

After that we'll translate them.

**Comment by danguita** [comment]
Just to keep it in mind, let's also take the user verification process communications into account: #75.

**Comment by furilo** [comment]
Subject: Bienvenido

Hola,

Tu registro se ha completado con éxito. Ahora puedes interactuar en SITE_URL como usuario registrado.

Puedes gestionar tus alertas desde tu cuenta: ACCOUNT_URL

Saludos

-- 
Altos Cargos y Agendas · Diputación de Valencia
dipvalencia.go.dival.es

**Comment by ferblape** [comment]
Right now all emails are translated.
