### ISSUE TITLE
Amend reference to municipality in data storage

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#1557]
Budgets data stored in ElasticSearch, contains a reference to the municipality identifier named `ine_code`. This reference  is an integer. To support organizations this identifier should be a string and we should probably rename it to something like `organization_id`.

There are a few steps we need to follow:

- add a new column `organization_id` and keep `ine_code`
- copy the values from `ine_code` to `organization_id`
- update the fixtures/tests and check everything works with the ES fixture data
- check if the staging and production ES schema can be updated to be a string
- check the queries against ES still work
- prepare a plan to migrate staging and production data.

**Comment by furilo** [comment]
This is in progress, right? Would you mind moving this to the appropiate column in Zenhub? Also, I'd only include the issue # in the PR instead of each commit.

**Comment by ferblape** [comment]
This has been released to production.
