### ISSUE TITLE
Logo Proporsal: Gobierto

### ISSUE THREAD

**Issue by tjulises** [PopulateTools/gobierto#1655]
Hey, I'm graphic designer and my aim is supporting open source projects and make my portfolio better. So, I can contribute on your project with making logo design. I am waiting your feedback! Have a nice day! :)

Best Regards,
TJ Ulises
Visual Communication Designer

**Comment by furilo** [comment]
Hi @tjulises, thanks very much for the offer! Currently we already have a logo you can see at: http://gobierto.es - So we are in no need of a new one ;)

Again, thanks for the offer!
