### ISSUE TITLE
Admin UI: People: Show a warning if changing tabs and data not saved

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#178]
re #177

**Comment by furilo** [comment]
@danguita you take care of this?

**Comment by danguita** [comment]
Sure 👌

**Comment by danguita** [comment]
@furilo Hope you don't mind me closing this one since it is already covered in https://github.com/PopulateTools/gobierto/issues/240 (PR https://github.com/PopulateTools/gobierto/pull/258).
