### ISSUE TITLE
Run tests against custom engine topic branch when relevant

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto#1798]
Sometimes when you develop a feature for Gobierto and a custom engine you make changes in both repositories.

For the tests to pass both for the Gobierto PR and gobierto master we should change  `script/custom_engines_ci_setup` so that when creating a PR in gobierto, if there is a branch in the engine with the same name, the scripts checks out that branch in the engine repository instead of `master`.

Try something like:

1. `cd` the engine repository in the CI server
2. `git checkout $CIRCLE_BRANCH`
3. If the exit code is OK, the branch exists. If it fails, checkout master instead.

**Comment by ferblape** [comment]
Implemented in https://github.com/PopulateTools/gobierto/pull/1947
