### ISSUE TITLE
Events date picker issues

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#1811]
If you go to GobiertoPeople > Person > Agendas and edit an event:

- [ ] ~it shows always the current time + the offset of the time zone. You can check this with any event in staging. If you edit and save the event it'll be recorded with a new time of + 2 hours, and so on~

- [x] when you pick a day, the date picker closes. If you want to edit the hours too you need to open it again

- [x] could we make the input editable so no need to use the date picker? could we make the hours input editable?

- [ ] it'd be great to link (bind) start and end dates for events and not for processes phases. So maybe we could think on a parameter that if active links the dates, otherwise it doesn't

**Comment by Crashillo** [comment]
This [helper](https://github.com/PopulateTools/gobierto/blob/master/app/helpers/gobierto_admin/gobierto_people/date_picker_helper.rb) solves the last point.

You only must identify which datepicker forms should have an offset value between start & end dates and edit those HTML using the helper

**Comment by ferblape** [comment]
I don't see what you mean. Binded datepickers behaviour is implemented here: https://github.com/PopulateTools/gobierto/blob/master/app/javascript/admin/modules/application.js#L87-L93

This is what should be configurable via a parameter.

**Comment by ferblape** [comment]
We'll solve the first point in #1837, it's a Ruby and Rails issue 💎
