### ISSUE TITLE
Styles issues

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#1831]
When the mouse is over a project the cursor should be a pointer instead of `text`

![screen shot 2018-08-03 at 11 15 22](https://user-images.githubusercontent.com/17616/43635150-8b05922a-970e-11e8-8f6a-a70d922e8801.png)

**Comment by Crashillo** [comment]
It's included in #1846, but thinking about it, I believe it was disabled in case of `"open_node": false`, that means, when you disallow the project level view. In such case, there's no link even you see the `pointer`
