### ISSUE TITLE
New option for budget receipt: allow user to enter values

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#1897]
We have to allow users to enter manual values for each field, while supporting the actual input method. I propose: 

- In the service conf textarea in the admin screen (http://esplugues.gobify.net/admin/gobierto_budgets/options) allow that we configure a "manual_input: true" value
- If manual_input = true, we would only need to define which rows we are going to ask for. Example: 
```
{
  "manual_input": true,
  "budgets_simulation_sections": [{
      "name_es": "IBI"
    },
    {
      "name_es": "Vehículo"
    },
    {
      "name_es": "Vehículo adicional"
    },
    {
      "name_es": "Vado de vehículos"
    }
  ]
}
```
- If manual_input = true, calculations in the front_end would have to be done differently. 
- Options for Esplugues (add them in staging when ready to do the demo):
```
IBI
Vehículo
Vehículo adicional
Vado de vehículos
```
- Please add documentation about this option. @ferblape where we should add this? (we have a standalone page for plans doc in the repo, but I feel we should have more integrated...) 
- Please provide a video demo of 1) entering the conf and 2) the end user experience.

Please review and comment @ferblape @Crashillo

**Comment by ferblape** [comment]
Ok to me

- if manual_input is enabled we should just display the current year column, right?
- I'd add a minium check in the user text field to test if the value is a number and it can be used in the calculations
- about the docs I suggest to:
  1. update the actual page: https://github.com/PopulateTools/gobierto/blob/master/docs/gobierto_budgets/receipt_format.md
  2. link that page from the admin, and open it in a new window or think in a first iteration of #996 that maybe reads markdown pages from the repository?

**Comment by furilo** [comment]
>
>    - if manual_input is enabled we should just display the current year
>    column, right?
>
> yes

>
>    - I'd add a minium check in the user text field to test if the value
>    is a number and it can be used in the calculations
>
> ok

>
>    - about the docs I suggest to:
>       1. update the actual page:
>       https://github.com/PopulateTools/gobierto/blob/master/docs/gobierto_budgets/receipt_format.md
>       2. link that page from the admin, and open it in a new window or
>       think in a first iteration of #996
>       <https://github.com/PopulateTools/gobierto/issues/996> that maybe
>       reads markdown pages from the repository?
>
> should we differentiate between admin and developer? or start in the same
place?

**Comment by ferblape** [comment]
Yeah, we should probably move a few pages from the `docs/` to the admin manual because they refer to things admin can do. I'll create an issue.

**Comment by Crashillo** [comment]
Check [this](http://madrid.gobify.net/presupuestos/recibo) out

**Comment by ferblape** [comment]
Two things:

- [ ] I'm able to introduce negative values, and I shouldn't
- [ ] Could you enable the "Tab" key to behave like the Enter?

**Comment by furilo** [comment]
Also, remember we talked about making the bg of the input white

And, put the instructions text where the year is, adding the year. So the text will end as: "Introduce las cantidades que has pagado para cada uno de los conceptos en 2018"
