### ISSUE TITLE
Decide calendar integration in People Module

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#192]
re #177

**Comment by ferblape** [comment]
There are two main calendar services online: Google Calendar and Microsoft (which covers Exchange, outlook, hotmail, office and many more).

Here there are some useful links:

  - Google Calendar
    - overview: https://developers.google.com/google-apps/calendar/concepts/
    - authorization: https://developers.google.com/google-apps/calendar/auth
    - sync: https://developers.google.com/google-apps/calendar/v3/sync
    - push notifications: https://developers.google.com/google-apps/calendar/v3/push
  - Exchange Online | Office 365 | Hotmail.com | Live.com | MSN.com | Outlook.com | Passport.com
    - overview: https://msdn.microsoft.com/en-us/office/office365/api/calendar-rest-operations
    - auth: https://msdn.microsoft.com/en-us/office/office365/api/use-outlook-rest-api#ShortRegAuthWorkflow

Both APIs are quite simple and similiar (calendar and events resources). What change is the way to sync the events.

Also, both APIs use OAuth. We would need a new screen for the user to Connect with the calendar service, probably in her settings page.

**Comment by ferblape** [comment]
We have splitted this issue in small ones: #637 and #590
