### ISSUE TITLE
Linecharts are broken

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#1961]
In observatory page: https://portalobert.esplugues.cat/observatorio

![screen shot 2018-10-18 at 17 21 05](https://user-images.githubusercontent.com/17616/47165438-3fde7280-d2fa-11e8-99b4-3aa4b361fc8d.png)

In budgets indicators page:  https://gobiernoabierto.getafe.es/presupuestos/indicadores/2018

![screen shot 2018-10-18 at 17 22 03](https://user-images.githubusercontent.com/17616/47165481-584e8d00-d2fa-11e8-8e00-174376eea38d.png)

Same JS error in both pages.

**Comment by ferblape** [comment]
Ok, a clue: in the rent distribution chart, bubbles used to have a tooltip, and now that tooltip is not working. Could be that the issue?

**Comment by Crashillo** [comment]
It seems a consequence. In `master` branch, tooltip is being displayed properly, and no error is thrown. Once the error is triggered, it breaks also the tooltip.

**Comment by ferblape** [comment]
Ok, it's fixed.
