### ISSUE TITLE
Unify settings management

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#197]
Right now we have two different ways of storing settings:

- the gem `Settings`, in the files `config/settings/*`
- the `APP_CONFIG` way

We should pick one of those and unify the code and the config files.

**Comment by danguita** [comment]
Just for the record, I would go for the `APP_CONFIG` (and whatever else `/config` files are needed) so that we reduce the number of dependencies 🙆

**Comment by ferblape** [comment]
I agree. I´ll pick this one, because it´s related with the Ansible environment setup.

**Comment by danguita** [comment]
Nice, go ahead 👍
