### ISSUE TITLE
Collection container updated to draft should avoid items rendered in the frontend

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#1973]
This issue affects to many pages in the application:

- gobierto agendas list of events
- process events
- participation page events
- ...

Also: check the activity subject. Instead of "page updated", should be "page unpublished" / "page published". If the page has also been updated, maybe we should generate two events, one for page attributes update and other for page visibility update.

**Comment by entantoencuanto** [comment]
The list of attachments of an issue or scope queries the `GobiertoCommon::CollectionItem` where the container is the corresponding associated term, but the visibility level is set by the `collection.collection_container` the collection_item belongs to. I'm going to fix the query to take into account the visibility given by the upper level container.
