### ISSUE TITLE
Observatory tooltip review in Windows browsers

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#1977]
Looks like the tooltip of the Economy and wealth graph doesn't work in Windows 7 and Windows 10 in browsers Chrome, Firefox and Edge.

![screen shot 2018-10-26 at 09 02 34](https://user-images.githubusercontent.com/17616/47571357-9ec66c00-d938-11e8-8522-8f6897bca59f.png)

**Comment by Crashillo** [comment]
I've just tried Chrome/Firefox/Edge in W10 and is working like a charm. IE is fully broken, instead. Let me give you a feedback about W7.

**Comment by Crashillo** [comment]
Funny. Now it's happening..... even in MacOS. Staging throws an error, in the chart, and I think it's causing the tooltip failure. The problem is how to debug it, because it doesn't happen in local environment. :(

**Comment by Crashillo** [comment]
In effect, that error was firing the tooltip failure. 
It was tested successfully on Chrome/Firefox/Safari in macOS, on Firefox/Chromium in Linux, on Chrome/Firefox in W7. Unfortunately on IE11 in W7, it seems barely every charts are broken.
It's deployed in staging
