### ISSUE TITLE
Broken links in admin/cms/sections

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto#1980]
http://madrid.gobify.net/admin/cms/sections

Generated URLs for preview links look like: 

http://madrid.gobify.net/admin/cms/gobierto_participation_section_path(section.slug%20,host:%20current_site.domain)

**Comment by ferblape** [comment]
I'd remove the page http://madrid.gobify.net/admin/cms/sections from the code and fix the breadcrumb of a section to be "Inicio >> CMS >> Sección del sitio" as in Collections http://madrid.gobify.net/admin/collections/13
