### ISSUE TITLE
Delete process stage pages when process is archived

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto#1995]
Related to: https://rollbar.com/Populate/gobierto/items/1298/?item_page=0&#instances

**Steps to reproduce:**

1. Create published process
2. Create page under the "Noticias" tab
3. Associate page to the default information stage
4. Archive process
5. Restore process
6. Go to the process "Noticias" tab, and try to destroy the page. It'll break because when the process was destroyed its stages were destroyed but not the process_stage_page associated to the information stage. This is because we're using `dependent: :delete_all` instead of `dependent: :destroy` [here](https://github.com/PopulateTools/gobierto/blob/master/app/models/gobierto_participation/process.rb#L30).

This generates two bugs:

1. The page can't be destroyed because it is already linked to a "unexistent" process stage
2. When the controller tries to display a message in the banner saying "This page cant be destroyed because it's already linked to X stage", [the link to the stage fails to be generated](https://github.com/PopulateTools/gobierto/blob/master/app/controllers/gobierto_admin/gobierto_cms/pages_controller.rb#L164).

**Testing**

I'd ensure this is fixed by modifying [this test](https://github.com/PopulateTools/gobierto/blob/master/test/integration/gobierto_admin/gobierto_participation/processes/archive_process_test.rb#L35) and checking that both the stages and the process stage pages were destroyed after archiving the process.

In order of this test to work, after replacing `delete_all` per `destroy` we have to complete the fixtures, because Rails verifies if a record is valid before calling its destroy method and right now they're not valid.

**Comment by entantoencuanto** [comment]
There is a callback preventing the destroy of an active stage. I'll move this logic to the admin controller
