### ISSUE TITLE
Deliver font-awesome assets packed in our assets

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#2113]
Right now fontawesome is included in two stylesheets:

app/assets/stylesheets/admin/application.scss
76:@import "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css";

app/assets/stylesheets/application.scss.erb
125:@import "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css";

The idea is to replace both assets by this gem: https://rubygems.org/gems/font-awesome-rails/versions/4.7.0.4

**Comment by ferblape** [comment]
@furilo @Crashillo can we update the version of fontawesome in the admin CSS to 4.7?

**Comment by furilo** [comment]
This seems a bit outdated, current version is 5.7. I've put it in
Drive/Recursos

https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself

**Comment by ferblape** [comment]
WIP in this branch: https://github.com/PopulateTools/gobierto/tree/2113-font-awesome-inline

Fontawesome v5 has new icon styles that we'll need to review and confirm.

**Comment by furilo** [comment]
Whay is the increase on the weight of assets when we include this?

**Comment by ferblape** [comment]
admin.css from 529.17kb to 370.48kb. It's strange but maybe having the styles inline is more efficient, or maybe v5 is smaller.

**Comment by ferblape** [comment]
I forgot to release this branch to staging for review, I'm deploying it right now.
