### ISSUE TITLE
Normalize and sanitize attachment file names

### ISSUE THREAD

**Issue by danguita** [PopulateTools/gobierto#212]
### Motivation

Right now we are setting file names manually every time an attachment file is uploaded through the `FileUploader` library. That may cause inconsistencies and both functional and maintainability issues, so let's avoid them by implementing a Service class that can act as interface to the actual file uploading library.

### Implementation notes

- [x] Refactor the current `FileUploader` lib by splitting it into a library to just deal with the file transport thing, and a Service class that may know a little about business logic.
- [x] Make the `FileUploader` service take kind of Site, Module, Resource and Attribute parameters to be able to build a normalized file name.
- [x] Also take care of sanitizing that file name.

/cc @ferblape

**Comment by ferblape** [comment]
👍
