### ISSUE TITLE
Implement an alternative uploader for file attachments

### ISSUE THREAD

**Issue by danguita** [PopulateTools/gobierto#213]
### Motivation

Dealing with file attachments may be a little annoying in `development` environment since every uploading process is actually reaching the AWS S3 bucket specified for uploads. It would be great to implement an alternative uploader to be used on certain environments and avoid hitting external services.

Please note that we are not hitting any of these external services in `test` environment.

### Implementation notes

- [x] Implement a local file uploader that writes the uploaded file to the local file system, à la Paperclip/Carrierwave.
- [x] Determine when to use one or another uploader, taking the current environment into account.

### Workflow notes

- Keeping it in back-log since it is not a priority for now.
- May depend on https://github.com/PopulateTools/gobierto/issues/212.

/cc @ferblape

**Comment by ferblape** [comment]
👍
