### ISSUE TITLE
Specify a cache validator

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2148]
From https://gtmetrix.com/reports/portalobert.esplugues.cat/lpYaWFpA

The following resources are missing a cache validator. Resources that do not specify a cache validator cannot be refreshed efficiently. Specify a Last-Modified or ETag header to enable cache validation for the following resources:

https://portalobert.esplugues.cat/assets/application-9d6ae7c32edb19c5739820d1769026e49840c203ddf5f898b809536e3f6c7b14.css
https://portalobert.esplugues.cat/assets/favicons/android-chrome-144x144-b7ba94428747702734324280e49c04ed5414f05b85d3252f88e0780107a76f8f.png
https://portalobert.esplugues.cat/assets/favicons/android-chrome-192x192-a898a53c6501ff01d0c1373be5b00c346c4ff8ef22094e27fd6df1d06dc83765.png
https://portalobert.esplugues.cat/assets/favicons/android-chrome-36x36-3ae850ceed499454ed8f474405a0b0bedcf6c902594eec606e9ac581a3a18819.png
https://portalobert.esplugues.cat/assets/favicons/android-chrome-48x48-5596574fa6c95d4ffe82da839b447a3f1104d70baec840c32c77ce6571c69248.png
https://portalobert.esplugues.cat/assets/favicons/android-chrome-72x72-9ea7bcf4a42c0ed1b4777eedb206531da9873b864bf2fb9935889bc9b8efb5b0.png
https://portalobert.esplugues.cat/assets/favicons/android-chrome-96x96-a740c2a789b079af7d92a5518e361ebcc779b19e77c1cf2af2862577bcea5d22.png
https://portalobert.esplugues.cat/assets/favicons/favicon-16x16-20c29f8c657793d4ef79e5d755383cebe3649b226702b19872d64194c59de8fe.png
https://portalobert.esplugues.cat/assets/favicons/favicon-194x194-d2140d53388d1c85bf851f1a05b34a7efb17d7fa32fdd2c58abd29cb2caf7e03.png
https://portalobert.esplugues.cat/assets/favicons/favicon-32x32-cacd2e6390787bd0031c19ba6c9398e21cf2ac285ab54966ce21ca62c91b039c.png
https://portalobert.esplugues.cat/assets/favicons/favicon-8bf18336222125c89200f3f0fc2cab966e4d712d2c701f191bd933fa0dcbf455.ico
https://portalobert.esplugues.cat/assets/favicons/favicon-96x96-901dafb7a000031e4c0109b760829fbb533296b71353aa71b1d94e48fcb066a8.png
https://portalobert.esplugues.cat/assets/illustrations/personaliza-607760cb9884f4293cb4928cde33e9c60c3de0328555e40d97ad932541eeac3a.jpg
https://portalobert.esplugues.cat/packs/budgets-3fb3a0b93bc6a93dab06.js
https://portalobert.esplugues.cat/packs/commons-b83e2995f992de67f87c.js

**Comment by furilo** [comment]
Does it make sense to use a CDN so it's them who manages this?

**Comment by ferblape** [comment]
Fixed in all our sites, it was an option that we included in our sites since 2015 but I wasn't sure we need it.
