### ISSUE TITLE
Activate HTTP/2

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2150]

**Comment by ferblape** [comment]
We already have it:

![screen shot 2019-03-06 at 16 42 48](https://user-images.githubusercontent.com/17616/53893661-e7044200-402e-11e9-9033-301f6f17fcd0.png)

**Comment by furilo** [comment]
Mmm... The Google Lighthouse Audit (inside Chrome) says otherwise: 

![image](https://user-images.githubusercontent.com/24740/53894037-a8bb5280-402f-11e9-8da7-74063cfd40a5.png)

**Comment by ferblape** [comment]
http2 is already implemented in the new app server
