### ISSUE TITLE
Admin Plans / New Save Widget - without Moderation

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2181]
Issues to implement new save widget. I leave for a second iteration all that has to do with moderation. 

http://madrid.gobierto.test:3000/sandbox/admin_plans_plan_projects_project

![image](https://user-images.githubusercontent.com/24740/54928345-0a2a5f00-4f14-11e9-832f-acfb671a2ff1.png)

- [ ] Buttons save-preview
- [ ] "Editing version N"
- [ ] Show past versions -> ¿just load version in UI?
- [ ] Status
- [ ] Published version
- [ ] Publish button
- [ ] Once a version it's published: the main button should be "Unpublish" 

We leave for further iterations: 

- Minor change (doesn't save version)
- Change published version (fine grain control)

**Comment by ferblape** [comment]
@furilo could you upload a bigger image?

**Comment by furilo** [comment]
Changed
