### ISSUE TITLE
Include descriptions for budget lines in gobierto sites

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#219]
It would improve current budget line page according to design (pasting design at the end as reference) 

re #69

I don't know currently how easy it would be to allow people to customize it. I see different levels: 

- a specific site wants to change it (it will probably have an UI to do it)
- a site admin wants to update the descriptions globally for all sites

![captura de pantalla 2016-09-12 a las 9 35 48](https://cloud.githubusercontent.com/assets/24740/18428091/5277ec4e-78cc-11e6-874e-53ff392a63db.png)

**Comment by jorgesancha** [comment]
@ferblape las saqué de aquí: https://www.boe.es/buscar/act.php?id=BOE-A-2008-19916

**Comment by ferblape** [comment]
Added all level 2 descriptions and some of level 3, but many of them are empty.

Maybe for level 3 and below we can refer to level 2 description, because they are quite extense and descriptive. Example for "Servicios sociales y de promoción social"

> Se imputarán a esta política de gasto los llevados a cabo por la Entidad local para desarrollar la asistencia social primaria: la promoción de la igualdad de género, promoción y reinserción social de marginados, así como para la gestión de los servicios sociales; prestación de servicios a personas dependientes y de asistencia social, residencias de ancianos y otros de naturaleza análoga; la evaluación e información de situaciones de necesidad social y la atención inmediata a personas en situación o riesgo de exclusión social. También se incluirán las transferencias finalistas a entidades y familias que colaboren en la consecución de estos fines. 

> Se incluirán los gastos correspondientes a la Administración General, que corresponderán a las actividades dirigidas a la planificación, coordinación, control, organización, gestión administrativa y desarrollo de funciones de apoyo de los distintos centros directivos que integran la política de gasto.
