### ISSUE TITLE
Implement "Attachment" Dynamic content field type 

### ISSUE THREAD

**Issue by danguita** [PopulateTools/gobierto#220]
### Motivation

In addition to the field types that are currently implemented, add the "Attachment" field type to let the User upload any file from her filesystem.

### Implementation notes

- [ ] When field has the "attachment" type, render a file input and let the currently configured adapter handle the file upload in the corresponding Form object.

**Comment by danguita** [comment]
@ferblape @furilo Hey, would you say this is still good to have? I'm leaving it in back-log from now.

**Comment by ferblape** [comment]
Yep, let's leave in the back log for the time being.

**Comment by danguita** [comment]
Alright, thanks mate.

**Comment by furilo** [comment]
- [ ] Add UI to upload and view attachment

**Comment by ferblape** [comment]
Duplicated #508
