### ISSUE TITLE
Allow moderators to unpublish projects changing moderation status

### ISSUE THREAD

**Issue by entantoencuanto** [PopulateTools/gobierto#2208]
If a moderator updates status of a project from approved to other status, ask if he wants to update publish status to unpublished.

**Comment by entantoencuanto** [comment]
- [x] At any moderation stage of the project, a moderator should be able to change the visibility level of the resource.
- [x] When a moderator changes from approved to any other stage and the resource is published, a link on the message should allow him to unpublish it

**Comment by entantoencuanto** [comment]
I've added publish/unpublish actions only available to moderators on each stage separated of the submit actions.

As editor:
![2208-editor](https://user-images.githubusercontent.com/446459/56315501-2064bd00-6158-11e9-85b3-61388bce38ef.gif)

As moderator:
![2208-moderator](https://user-images.githubusercontent.com/446459/56317299-af73d400-615c-11e9-9fcb-66ead4be92ef.gif)

**Comment by furilo** [comment]
Why are you creating another Publish/Unpublish button? I'd keep the one we already have unless there is a powerful reason.

**Comment by entantoencuanto** [comment]
> Why are you creating another Publish/Unpublish button? I'd keep the one we already have unless there is a powerful reason.

The actions for editors and moderators may be different:
For editors the Publish/Unpublish action is allowed only if the project has an approved moderation status. The editors also can change the moderation status from not sent to sent. All these actions are available with the same button in the first element of widget:
<img width="277" alt="Screen Shot 2019-04-23 at 14 56 00" src="https://user-images.githubusercontent.com/446459/56582672-128bbd80-65d8-11e9-81fd-15ecf1a801a1.png">
<img width="278" alt="Screen Shot 2019-04-23 at 14 56 17" src="https://user-images.githubusercontent.com/446459/56582679-17507180-65d8-11e9-81fa-9406c44bf185.png">
<img width="277" alt="Screen Shot 2019-04-23 at 14 56 31" src="https://user-images.githubusercontent.com/446459/56582693-1f101600-65d8-11e9-9a2e-8ebd9012a97c.png">
<img width="277" alt="Screen Shot 2019-04-23 at 14 56 42" src="https://user-images.githubusercontent.com/446459/56582699-23d4ca00-65d8-11e9-94a2-c589794504a5.png">


For moderators the Publish/Unpublish action has to be allowed regardless the moderation status. If we enable and use the button of the editors box to publish/unpublish at each moderation stage, for an admin with moderation and edition permissions which action should have for a not sent project? send or publish?

**Comment by entantoencuanto** [comment]
The moderator publish/unpublish action has been replaced by a submit button

For moderators:
![2208_2-moderator.gif](https://images.zenhubusercontent.com/59e88250a468affe6df7489e/5ca1f9df-0474-44b4-b763-16cf0120b916)

For editors:
![2208_2-editor.gif](https://images.zenhubusercontent.com/59e88250a468affe6df7489e/1761a3b0-a391-43ab-939c-5518e8bc59df)

**Comment by ferblape** [comment]
👍 I can see it's now the same action and when the button is available in the moderator menu, the other one is disabled.
