### ISSUE TITLE
Changes in projects index filters

### ISSUE THREAD

**Issue by entantoencuanto** [PopulateTools/gobierto#2212]
Add filters to projects tab:
- [ ] Moderation status
- [ ] Edition (my projects, projects I can edit...)
- [ ] Author

Remove current first level category filter

**Comment by ferblape** [comment]
Just one small change, could you make the filter by text to ignore the case of the strings?

**Comment by entantoencuanto** [comment]
> Just one small change, could you make the filter by text to ignore the case of the strings?

Before:
![2212-before](https://user-images.githubusercontent.com/446459/56598089-162d3d80-65f4-11e9-814e-e461d2c0e544.gif)

After:
![2212-after](https://user-images.githubusercontent.com/446459/56598851-9b652200-65f5-11e9-9479-95b0347e369f.gif)

**Comment by ferblape** [comment]
This works fine. We are creating a new issue to make filters easier to use.
