### ISSUE TITLE
Plans / Conf / Import-Export links position

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2222]
They should be in the sidebar column, below the save widget

And each one enclosed on a `<div class="m_v_1"></div>`

**Comment by entantoencuanto** [comment]
I've made the changes, but save widget has `stick_in_parent` class. I've created an `admin_side_actions` class for the links with `stick_in_parent`, but there is a small gap where admin widget and links block get ovelapped

![2222-after.gif](https://images.zenhubusercontent.com/59e88250a468affe6df7489e/65aa1bb1-4717-4138-bb5b-5584dfd9413d)

**Comment by furilo** [comment]
Where is the code for this? I don't see any PR related.

**Comment by entantoencuanto** [comment]
Here is the commit containing all changes: https://github.com/PopulateTools/gobierto/pull/2191/commits/f0a60accdb2d23b7716100fdbcd5226eacec17b9

It is also merged into staging, you can take a look, for example. at: http://madrid.gobify.net/admin/plans/12/edit

**Comment by ferblape** [comment]
This is not fixed yet, right?

**Comment by entantoencuanto** [comment]
Right

**Comment by furilo** [comment]
Done in https://github.com/PopulateTools/gobierto/commit/47fcf5a7c074f0a81dadd9d3f31d442966ba0d76
