### ISSUE TITLE
Plans / Project creation / Vocab terms not being shown

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2223]
In talavan.gobify.net I have this vocab: 

![image](https://user-images.githubusercontent.com/24740/55950469-4ae4e080-5c55-11e9-8878-02ba611d141f.png)

When creating a project, only one term shows: 

![image](https://user-images.githubusercontent.com/24740/55950459-43bdd280-5c55-11e9-87a7-411339066dbc.png)

**Comment by entantoencuanto** [comment]
I've updated the order of the categories order to use the position correctly
