### ISSUE TITLE
Plan summary in plan tab

### ISSUE THREAD

**Issue by entantoencuanto** [PopulateTools/gobierto#2234]
Related with: #2213

Add global progress percentage and count of projects grouped by moderation stage according to: http://gobify.net/sandbox/admin_plans_plan.html

Some moderation stages are not included in the sandbox design:
* Not sent
* Rejected
* With moderation stage not defined.

For the first two, initially I'll use red and for the undefined status the same color as total.

<img width="388" alt="Screen Shot 2019-04-16 at 16 54 37" src="https://user-images.githubusercontent.com/446459/56220266-73f7dd80-6068-11e9-9185-6103590edda0.png">

<img width="534" alt="Screen Shot 2019-04-16 at 17 07 07" src="https://user-images.githubusercontent.com/446459/56221210-1ebccb80-606a-11e9-86e2-0cf3eda63e44.png">

**Comment by entantoencuanto** [comment]
There is a problem with the boxes height, I'm trying to adjust the styles to make both have the same height without forcing a fixed height.

![Screen Shot 2019-04-16 at 18.46.14.png](https://images.zenhubusercontent.com/59e88250a468affe6df7489e/ef7b63f3-b526-4821-964b-051409732397)

![Screen Shot 2019-04-16 at 18.45.23.png](https://images.zenhubusercontent.com/59e88250a468affe6df7489e/12001e45-fe19-49bc-b776-709cea11ffb0)

**Comment by furilo** [comment]
I'll provide some code to add.

**Comment by furilo** [comment]
New design:

![image](https://user-images.githubusercontent.com/24740/56672778-4c7fc100-66b7-11e9-8e2c-d3dc69dd05a1.png)

(code in this branh: https://github.com/PopulateTools/gobierto/pull/2252 - sorry for the branch-mess)
