### ISSUE TITLE
Site municipality autocomplete is not being triggered to the proper URL

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#226]
Right now, when creating or updating a site, the autocomplete tag for municipalities is not triggering the request to the url defined in `data-autocomplete-url` but to the current url.

See the log trace:

```
Started GET "/admin/sites/new?query=Ses" for 127.0.0.1 at 2017-01-11 15:53:40 +0100
Processing by GobiertoAdmin::SitesController#new as TEXT
  Parameters: {"query"=>"Ses"}
...
```

**Comment by danguita** [comment]
Let me check it 👀
