### ISSUE TITLE
Plans / Evaluate steps and effort to have custom fields for instances in addition to models

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2302]

**Comment by entantoencuanto** [comment]
## Custom fields at instance level

Currently the custom fields are defined for all instances of classes by site. The idea is to:
* Add another configuration in modules defining classes which admits definition of custom fields in their instances
* Editing an element which admits custom fields, the form shows custom fields defined for the site and model and custom fields provided by the instance the element belongs to. To add flexibility, in this case the instance should be provided by the controller as a "context instance" (for example, a project can belongs to many plans, but the project form is nested under a plan, so the context can be provided by the controller)

Steps:

* Add polymorphic relation between custom_fields and instance (current global custom fields will not have instance defined)
* Create a controller to edit, at level instance, the custom fields. The controller and views are close to current global but:
  * Must check if the instance belongs to a class allowed to define custom fields
  * Must allow the creation of custom fields only for the classes configured for the module, not for other modules
* In the custom field form use a block for the global configuration and other one provided by a context instance
* Adapt the form to generate and accept custom fields

This can take 2 days

## Custom fields which admits a list

* Add array flag to custom field type definition:
  * With this type of field enabled for a model, in the form an admin should have a CRUD of fields of a type.
  * Add an options JSON attribute to custom_field_record. Initially, for array custom field types a `title_translations`. In the future this field also could store an "internal" flag, for example. The elements of options can be defined in the custom_field type (options for array elements)
  * Add `visibility_level` to custom_field_record
  * Add a position as normal attribute with orderable concern?

Add admin interface to array custom fields:

 * The admin should be able to create and delete elements of array
 * The admin should be able to reorder elements of array?
 * The elements of the array should be edited on the fly and updated when the entire form is sent

This can take 3-4 days

## Admin interface of dataGrid custom field type:

 * Allow edition of title of existing and new columns
 * Allow deletion of columns
 * Allow deletion of rows
 * Initialize new grids with a grid with a column for indicators and a empty column of data.
 
1-2 days
