### ISSUE TITLE
Plans / Front / JSON: separate structure from projects content

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2314]
In order to reduce the weight and processing time of the JSON used in the front, separate in different calls: 

1. Main call which loads the structure and project list (same call as we have in the admin, so potential perfomance improvements applies to both. Analyze how projects in draft/not published affects this call)
2. Individual calls to load the content of each project

**Comment by entantoencuanto** [comment]
The decorator which generates the data makes use of a query. The current query doesn't take into account the visibility level of the belonging projects. By including a condition on visibility level, the plan tree and accumulated values should be affected and only the global progress should be corrected.

There is a problem in admin part. Should we also ignore the not published projects for accumulated values to have the same data in front and categories admin? Should we display the not published projects in categories or display them in a different way?

**Comment by furilo** [comment]
If project not visible (this includes not approved), don't take into account to calculate the progress.
