### ISSUE TITLE
Include a default installation footer?

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#232]
We would show a Gobierto logo (and maybe Populate's) in the footer.

**Comment by ferblape** [comment]
Not sure if we should add Gobierto icon instead of Populate icon (and keeping the same sentence) . In sites pages we don´t have any reference to Gobierto, as we do in the comparator.

**Comment by furilo** [comment]
Both logos or just Gobierto's? For a real site, we won't be showing any probably. For the Madrid demo maybe it makes sense to show Populate's, as the Gobierno one will be shown on the demo bar.

**Comment by ferblape** [comment]
Ok then
