### ISSUE TITLE
Blog post: Missing translation & the double radio button

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#233]
![captura de pantalla 2017-01-12 a las 16 09 55](https://cloud.githubusercontent.com/assets/24740/21895041/935d8762-d8e1-11e6-8188-508d9bde8496.png)

**Comment by danguita** [comment]
Same as in https://github.com/PopulateTools/gobierto/issues/231#issuecomment-272190165, can't reproduce here 😕 

![screen shot 2017-01-12 at 4 21 04 pm](https://cloud.githubusercontent.com/assets/126392/21895474/2b8249aa-d8e3-11e6-9d7e-aa4c72a4ad72.jpg)

It is probably related to your local environment. Let's sync your `stable` branch and restart the app server when you have some time.
