### ISSUE TITLE
Simplify the label for buttons

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#234]
Right now we have: Crear post, Actualizar declaración, ... In some situations the column is narrow, so the text gets cut, or paddings are not respected: 

![captura de pantalla 2017-01-12 a las 16 21 41](https://cloud.githubusercontent.com/assets/24740/21895483/362718f4-d8e3-11e6-8cb5-544c98151831.png)

So I would just leave the verb: Crear, Guardar...

**Comment by danguita** [comment]
No prob. Would you do so in every single case?

**Comment by furilo** [comment]
In the back at least, yes.

**Comment by danguita** [comment]
Alright, it makes perfect sense to me 👌
