### ISSUE TITLE
Plans / Plugin: Human Resources

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2346]
This plugin, using #2343 will provide a way for users to assign human resources to a project. This might be an iteration from #2344 as data structure and UI is very similar: An admin must:

- be able to add N resources to a project in the form of a slickgrid data table
- the plugin will define the structure of the available columns: 
  - resource type (autosuggest from vocabulary)
  - Cost
  - Start Date
  - End Date
- the first column will allow to select a **resource type** from a vocabulary.
  - pending:
    - decide how to configure the vocabulary for a given custom field-plugin
    - define an API so an external system can retrieve the Terms list
- the front-end component will write to the plugin hidden field after each edit of the user, a JSON representation of the data

**Comment by ferblape** [comment]
For start and end dates, there's a special editor of type calendar integrated in Slickgrid that uses https://flatpickr.js.org/getting-started/.

Here's an example: https://6pac.github.io/SlickGrid/examples/example-autocomplete-editor.html
