### ISSUE TITLE
Missing translation: person_posts.create.success

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#235]
When creating/saving a post

http://madrid.gobierto.dev/admin/people/people/933465536/blog/585972796/edit

translation missing: es.gobierto_admin.gobierto_people.people.person_posts.create.success

**Comment by danguita** [comment]
Hey, that seems to be the same outdated locale thing, please restart your server. Can't reproduce here.

posts/update action:

![screen shot 2017-01-12 at 4 25 54 pm](https://cloud.githubusercontent.com/assets/126392/21895724/fc826922-d8e3-11e6-8c6b-ce94a7c4391c.jpg)

posts/create action:

![screen shot 2017-01-12 at 4 27 33 pm](https://cloud.githubusercontent.com/assets/126392/21895745/0c44e04c-d8e4-11e6-9c17-9c365b22b5cc.jpg)

**Comment by furilo** [comment]
yeah sorry, my fault! 😞
