### ISSUE TITLE
Content blocks: respect tab order

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#238]
When you are entering a row, fill the last input and click on the TAB, it goes to the browser's url box (at least in Safari). It should go to the "Add" button.

**Comment by danguita** [comment]
@furilo We have just checked this one and there is nothing wrong with the tab index. As far as I know, Safari ignores certain elements in the tab index cycle, so what you mentioned is the default behavior in this and any other forms.

We have also found that there is an advanced preference to allow reaching any kind of element by hitting the tab key:

![screen shot 2017-01-18 at 12 22 16 pm](https://cloud.githubusercontent.com/assets/126392/22062331/78b3b1d8-dd79-11e6-9e4d-29ce6617e790.jpg)

Would you say we can just close this one?

**Comment by danguita** [comment]
I'm keeping this in back-log until we figure out how to deal with that Safari's weird thing.

**Comment by ferblape** [comment]
I have checked and with that option the tabs work OK 👍

**Comment by danguita** [comment]
Yep, Chrome and Firefox behave well, so I guess this is a weird but known behavior in Safari. I would just move on.
