### ISSUE TITLE
Plans / Allow other admins as editors of a project

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2380]
If I'm a moderator or an editor owner of a project, I should be able to grant view+edit access to a project to other editors. This UI should live inside a project. 

- [X] UI 
  - Code in #2396 - https://github.com/PopulateTools/gobierto/tree/2380-allow-other-admins
  - http://madrid.gobierto.test:3000/sandbox/admin_plans_plan_projects_project.html
  - New "Permissions" button in the top right of the item
    ![image](https://user-images.githubusercontent.com/24740/60287121-6cc73880-9911-11e9-82bc-73fca2afa456.png)
  - This opens a modal: 
    ![image](https://user-images.githubusercontent.com/24740/60287153-7badeb00-9911-11e9-8874-d3688067c959.png)
      - I've left a placeholder for a select2. This select2 will show existing admins in the system 
        - To discuss: only non-priviledged admins, as they already have access? Or all admins, so they receive an invitation to the item?
- [ ] Implementation
  - In the "Permissions" button - add the number of users with permission

**Comment by entantoencuanto** [comment]
Steps:

- [ ] Allow the creation of admin groups with only one permission. An editor permission which resource is an instance of project / GobiertoPlans::Node. ~~These kind of groups should not appear in the normal admin groups list.~~
- [ ] Add an enum to the admin groups model adding a group type for this kind of group (maybe `system`?)
- [ ] Add a callback after creation of a project creating an editors group with the author as first member.
- [ ] Add controllers and views to admin members of editors group of a project:
  - [ ] Use a select2 with the list of all admins with access to the site not belonging to the group
  - [ ] Only the author and a moderator can edit the list (and managers). ¿Any other kind of admin should be able to see the list?
  - [ ] Add site activities when members of the group are created or deleted.
  - [ ] Block deletion of owner and admins included in the list with manager or higher permissions from the list
