### ISSUE TITLE
Plans / Save Widget design iteration

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2395]
Two changes: 

1. Instead of a text link for "view versions", we switch to an icon

From 
![image](https://user-images.githubusercontent.com/24740/60286953-fe827600-9910-11e9-9aab-369606a53e34.png)

To
![image](https://user-images.githubusercontent.com/24740/60286969-06dab100-9911-11e9-8680-579d699922f8.png)

2. We move the Moderation box to a popover

From 
![image](https://user-images.githubusercontent.com/24740/60287003-1d810800-9911-11e9-8319-f889ac3d99de.png)

To
![image](https://user-images.githubusercontent.com/24740/60287010-2376e900-9911-11e9-8f5f-39720a1a3ff3.png)

On hover
![image](https://user-images.githubusercontent.com/24740/60287017-2a056080-9911-11e9-8802-17b2bcff5d1b.png)

Front-end code in https://github.com/PopulateTools/gobierto/pull/2396 -https://github.com/PopulateTools/gobierto/tree/2380-allow-other-admins

**Comment by amiedes** [comment]
@ferblape @furilo regarding what we've discussed about restoring the "Save moderation action" button either with an Ajax call or by putting the "Save" button within the popup:

We don't have a specific controller action for just updating the moderation status, so either we implement it or assume that any project update we trigger (Ajax or button) **will update all the attributes** (even if it's placed within the moderation popup).

I find this behavior misleading so what I'd do is only leave the upper save button:

![Captura de pantalla 2019-07-10 a las 13 03 22](https://user-images.githubusercontent.com/9287468/60964302-3925de80-a313-11e9-85c2-c8b7bbf3164c.png)

and display it both for editors and moderators. What do you think?
