### ISSUE TITLE
Content blocks: warning if you have added content and click on "Add new block"

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#240]
I had added several rows for a block, and thought that it was being saved; then went to add a new block, and came back to find out that nothing was saved ;) 

So: show a warning it you are leaving the page with the content unsaved. Don't know if we should think about something general, applicable to any form/page. What do you think @ferblape ?

**Comment by danguita** [comment]
As reported in https://github.com/PopulateTools/gobierto/issues/178, I was thinking of just going for a global solution at Admin namespace level. Anyways it's always good to be aware of very specific cases like these so that we can take special care of them. How does it sound to you?

**Comment by furilo** [comment]
Ok great, let's go for a global solution. Please reorg issues (close/new/...) as it fits you best.

**Comment by ferblape** [comment]
I was about to say the same as @danguita, so 👍

**Comment by danguita** [comment]
Alright, thank you guys 👌

**Comment by danguita** [comment]
Hey guys, I have ended up implementing that generic component so we can take advantage of it across the entire Admin area. I think that it would be useful in most cases so it is enabled everywhere by default. What do you think? Let's check it out at https://github.com/PopulateTools/gobierto/pull/258.

**Comment by ferblape** [comment]
It's great to have a generic solution for everything, thank you! Closing in favour of #258

**Comment by furilo** [comment]
+1 to enable it by default everywhere!
