### ISSUE TITLE
Plans / Improve the JS Alert when publishing a project for the first time

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#2401]
Improve the text of the JS Alert when publishing a project for the first time: 

"You are going to publish this project, so any user will be able to see it in the front-end."

**Comment by furilo** [comment]
I think this is the expected behaviour, since this action involves
publishing the project for the first time? Maybe we should improve the
alert message to something like: "You are going to publish this project, so
any user will be able to see it in the front-end."

**Comment by ferblape** [comment]
Agree
