### ISSUE TITLE
GobiertoPlans / Improvements in progress plugin

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#2402]
Follows #2347 

1. If the custom field referenced in the progress plugin is defined in different level (i.e the progress plugin is defined at instance level and the human resource plugin at plan level) the plugin shou ld find the custom field 
2. add a value by default to the configuration
3. add documentation about how to configure the progress plugin. Add a link (?) to that specific documentation section
4. if the configuration is incorrect and references to an invalid custom field, it should notify via Rollbar
5. rake task doesn't work when the custom field has been defined at global level, not at instance level.
6. You can't save a project:

![Screen Shot 2019-06-28 at 16 06 18](https://user-images.githubusercontent.com/17616/60347898-b326a100-99be-11e9-9ea5-339553cce392.png)

**Comment by entantoencuanto** [comment]
Also:
- [ ] In the default configuration use only a list of uids, the use of `custom_field_ids` and `custom_field_ids` is confusing.
- [ ] Validate the configuration: Raise validation errors if the uids refers to non existing fields or fields not implementing the `progress` function.
- [ ] Create site activities when update progress task is executed.

**Comment by entantoencuanto** [comment]
The point 6 is fixed via #2405

**Comment by furilo** [comment]
Create new issues for those 3 remaining points and close this ASAP.

**Comment by entantoencuanto** [comment]
Remaining tasks moved to #2419
