### ISSUE TITLE
GobiertoPlans / Add functions to human resources

### ISSUE THREAD

**Issue by entantoencuanto** [PopulateTools/gobierto#2408]
Add 2 functions In human resources replacing cost
  * planned_cost: The sum of all the costs of the human resources
  * executed_cost: The current cost function. The sum of the costs of each human resource up to current date

**Comment by ferblape** [comment]
If the dates of all the human resources are in the future the plugin returns a Not a number error.

**Comment by amiedes** [comment]
Closed via https://github.com/PopulateTools/gobierto/pull/2420
