### ISSUE TITLE
Content blocks: format content according to its field type?

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#241]
![captura de pantalla 2017-01-12 a las 17 25 16](https://cloud.githubusercontent.com/assets/24740/21898129/196dc6c8-d8ec-11e6-8a8f-0a84d0b616c6.png)

If the field is Currency, let's format the output. 

Also, if you enter a formatted number (ie. 123.456,98) it looses the quantity. 

We can solve the previous problem if we implement some format-as-you-type system (ie. https://nosir.github.io/cleave.js/ - but let's think if we can solve it with existing included libraries to avoid including more)

**Comment by ferblape** [comment]
I'm going to close this issue. At the end, storing the numbers with a format is not a big deal because the spreadsheets work fine with the decimals.
