### ISSUE TITLE
Plans / Create site activities when update progress task is executed

### ISSUE THREAD

**Issue by entantoencuanto** [PopulateTools/gobierto#2419]
Create an activity in gobierto and call from progress engine

**Comment by furilo** [comment]
Duplicated #2431 ?

**Comment by entantoencuanto** [comment]
I'ts a little bit different, this activity is created after the execution of the task for all the projects and the other one is created when admins create, update or delete single projects.

**Comment by furilo** [comment]
Shouldn't this be the same? Basically we have to create activity when project attributes get updated. Right?
