### ISSUE TITLE
Plans / Order of custom fields is not respected

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2421]
This order: 

http://dip-huelva.gobify.net/admin/custom_fields/module_resources/gobierto_plans-node?instance_id=28&instance_type=gobierto_plans-plan

![image.png](https://images.zenhubusercontent.com/59da7a2db0222d5de47ac5ba/eb854f16-55bf-4bf0-a8f2-d1c382db1991)

Should be the one in a project page, but it is not: 

http://dip-huelva.gobify.net/admin/plans/28/projects/10530/edit

![image.png](https://images.zenhubusercontent.com/59da7a2db0222d5de47ac5ba/2665672e-a89a-4992-b607-2bc9ce8292c0)

**Comment by amiedes** [comment]
Closed via https://github.com/PopulateTools/gobierto/pull/2420
