### ISSUE TITLE
Plans / Permalinks last level (Project detail)

### ISSUE THREAD

**Issue by Crashillo** [PopulateTools/gobierto#2424]
When `open_node` property is set to `true`, it shows detailed information about a project, after you open the table of projects, and click any.

That action sets a permalink in the address bar, which is not accessible again, due to you need the previous-mentioned step to display it.

So, the point is, handle this special casuistic when `open_node` is enabled.

**Comment by Crashillo** [comment]
@amiedes when you merge #2408, this will be solved there. See https://github.com/PopulateTools/gobierto/pull/2420/commits/82ea41bb0501fdd996dda5c8b8256dc7a8d5d45c

**Comment by amiedes** [comment]
Closed via https://github.com/PopulateTools/gobierto/pull/2420
