### ISSUE TITLE
Plans / Custom fields plugins > Fix select2 styles

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto#2425]
There's a styling issue when expanding the selec2 from the last row:

![image](https://user-images.githubusercontent.com/9287468/60353148-b2dfd300-99c9-11e9-8ca4-96aedb98cf8e.png)

**Comment by furilo** [comment]
Should we also remove the slight margin? 

![image](https://user-images.githubusercontent.com/24740/60987660-62119800-a342-11e9-970d-e4b4e92d6343.png)

**Comment by Crashillo** [comment]
Sometihng like that:

![imagen](https://user-images.githubusercontent.com/817526/61035445-6e8c0400-a3c7-11e9-91e4-28de6e82d7b8.png)

**Comment by furilo** [comment]
Go
