### ISSUE TITLE
Plans-Admin / Private and Public name for Vocabularies? 

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2426]
I created a set of vocabularies for the Demo Plan prefixing them so its not chaos: 

![image.png](https://images.zenhubusercontent.com/59da7a2db0222d5de47ac5ba/c3368d00-cbdb-4a63-af93-0b1d8b8a5972)

But now in the front...

![image.png](https://images.zenhubusercontent.com/59da7a2db0222d5de47ac5ba/74049385-4081-4daf-b099-ef21f0e48281)

Would it make sense to have a private and public name for the vocab?

**Comment by furilo** [comment]
ping @entantoencuanto @ferblape

**Comment by entantoencuanto** [comment]
The vocabularies have a name and a description. We can use the description if present instead of the name.

**Comment by amiedes** [comment]
A pragmatic (and dirty) alternative is to hide the prefix using the plugin code (it's straightforward).

If you thing we may use the private/public name for other use cases I'd go for that. But if not I'll just strip the name from the plugin.

**Comment by amiedes** [comment]
I deleted my comment, since this code is not from the plugins but from the common custom fields.

**Comment by furilo** [comment]
> The vocabularies have a name and a description. We can use the description if present instead of the name.

Is this intuitive enough? I'd aim that as an admin you understand the possibilities of the system without looking at the docs.

**Comment by entantoencuanto** [comment]
> > The vocabularies have a name and a description. We can use the description if present instead of the name.
> 
> Is this intuitive enough? I'd aim that as an admin you understand the possibilities of the system without looking at the docs.

Yes. Then the best solution is to use a public name attribute.

**Comment by ferblape** [comment]
Hmmmm, but the name of the custom field in the front is given by the name of the custom field in the admin and not by the name of the vocabulary:

![Screen Shot 2019-07-08 at 10 43 21](https://user-images.githubusercontent.com/17616/60796175-4012ec80-a16d-11e9-8b11-0256df99a31a.png)

Why not naming the custom fields without the prefix given that they are scoped at plan level?

**Comment by furilo** [comment]
>the name of the custom field in the front is given by the name of the custom field in the admin and not by the name of the vocabulary

😮 

thank goodness that some of us retains a little intelligence ...
