### ISSUE TITLE
Speedup tests > Bulk all budgets seeds at once

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto#2429]
Modify the budgets factories so when running `BudgetsSeeder.seed!` we can create all documents in a single network request.

**Comment by ferblape** [comment]
FYI @amiedes. I'm solving this with https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-api/lib/elasticsearch/api/actions/bulk.rb#L70

From 12 minutes to 9 minutes again.
