### ISSUE TITLE
Improve the texts in place summary numbers when updating year

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#249]
Now if you update a year, we keep showing the same text: "Según datos de este año, debemos 7429,7M€, 17,04% más que hace un año." which feels weird and it's not accurate. 

![captura de pantalla 2016-09-14 a las 17 06 16](https://cloud.githubusercontent.com/assets/24740/18517729/922a9ef4-7a9d-11e6-9038-5badf2b2ba1c.png)

cc @jorgesancha

**Comment by jorgesancha** [comment]
![image](https://cloud.githubusercontent.com/assets/86218/18531603/67644e42-7ad7-11e6-8ffa-75dfa842906f.png)

He simplificado un poco.
