### ISSUE TITLE
Admin: Can't select site

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#250]
In http://gobify.net/admin when you click on a site, you only get the page you are on reloaded

![captura de pantalla 2017-01-17 a las 15 36 15](https://cloud.githubusercontent.com/assets/24740/22024568/b23d1ae8-dcca-11e6-97e1-955147e7dc2b.png)

**Comment by danguita** [comment]
Since we are using sessions to keep the site context, could it be related to the session store configuration for that domain? Are the rest of session-based resources, such as for Admins and Users sign in, working just fine?

This is not happening on my development env. Let me know if I can help further.

/cc @ferblape

**Comment by furilo** [comment]
OK, seeing it with @ferblape I saw the site is being changed, but since you are left in the same page, it seems that nothing has changed. I mean: if you are editing one site's properties and you use the dropdown to select another site, you are left in the same original site you were in. So it seems nothing has changed. 

I would expect that you get redirected to the same page but for the site you have changed to. What do you think?

**Comment by danguita** [comment]
Yeah, now I see. I guess you were on a `sites/edit` page (the one titled with "Personalizar site" in it) when switched Sites. As you mentioned, we are redirecting the user to the same URL she came from, so in this very specific case it is correct but not much user friendly. I would say covering this specific scenario won't hurt, how about letting me take care of it now?

**Comment by danguita** [comment]
Hope you don't mind I picked up this one and took care in https://github.com/PopulateTools/gobierto/pull/259. I think it's a good improvement anyways, thanks for reporting 👍
