### ISSUE TITLE
Custom Fields / Migrate existing indicators and human resources records to table records

### ISSUE THREAD

**Issue by entantoencuanto** [PopulateTools/gobierto#2508]
- [ ] Create table custom field plugins with compatible configuration
- [ ] Move records association to belong to new custom fields
- [ ] Adapt payload keys replacing `human_resources` or `indicators` with table custom field uid
- [ ] Ensure the data generated in front remains unchanged

**Comment by furilo** [comment]
We can do this by hand since all data is test data.

**Comment by entantoencuanto** [comment]
Perfect. The only point is the data generated in front. I'll take a look.
