### ISSUE TITLE
JS error on bubbles when clicking the year

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#2645]
1. Go to budgets home
2. Wait for bubbles to load
3. Click in a year of the bubble
4. 💥  https://rollbar.com/Populate/gobierto/items/2809/

**Comment by amiedes** [comment]
@Crashillo ping me when you've fixed this and I'll add some tests in the PR

**Comment by Crashillo** [comment]
I have finally figured this out. There's something weird when we do: `import * as d3 from "d3"`, webpack does some internals what breaks the original library.
The solution (check the PR) is about to import only those function we actually use for each chart. The workaround I found for `transition` events will be fixed doing this.

Perhaps we should revert this PR https://github.com/PopulateTools/gobierto/pull/2614 and apply the proper changes now
