### ISSUE TITLE
JS when hovering on budget lines year

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#2646]
1. Go to budgets home
2. Scroll down to lines chart
3. Hover on a year
4. Data is not reloaded and two JS errors appear:

![Screen Shot 2019-10-31 at 08 07 39](https://user-images.githubusercontent.com/17616/67926150-904b0a00-fbb5-11e9-9007-12b72dce5f5a.png)

https://rollbar.com/Populate/gobierto/items/2808/
https://rollbar.com/Populate/gobierto/items/2807/

**Comment by amiedes** [comment]
@Crashillo ping me when you've fixed this and I'll add some tests in the PR

**Comment by Crashillo** [comment]
Same problem as https://github.com/PopulateTools/gobierto/issues/2645#issuecomment-548332400
