### ISSUE TITLE
Review and complete event notifications

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#267]
Follow up of #223

In #223 a few events were implemented. We need to review them, add or remove as we consider, and review the emails.

**Comment by danguita** [comment]
These are the attributes we've subscribed to so far (from https://github.com/PopulateTools/gobierto/pull/225):

>   - `GobiertoPeople::Person`
>     - `name`
>     - `charge`
>     - `bio`
>     - `visibility_level`
>   - `GobiertoPeople::PersonEvent`
>     - `title`
>     - `starts_at`
>     - `ends_at`
>   - `GobiertoPeople::PersonPost`
>     - `title`
>     - `body`
>     - `visibility_level`
>   - `GobiertoPeople::PersonStatement`
>     - `title`
>     - `published_on`
>     - `visibility_level`
