### ISSUE TITLE
Upgrade to Rails 6

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#2686]
Migrate to the latest version of Rails 6 published. This guide would help: https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-2-to-rails-6-0

Probably it'll be very difficult to activate Zeitwerk (see https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#autoloading), so it could be splitted in two PRs:

- first, migrate to Rails 6.x with the traditional autoloading style
- second, activate _6.x settings_ to use Zeitwerk

**Comment by ferblape** [comment]
Description updated

**Comment by entantoencuanto** [comment]
Breaking default 6.0 changes: https://medium.com/@dylansreile/rails-6-0-new-framework-defaults-what-they-do-and-how-to-safely-uncomment-them-586146f371e8

**Comment by ferblape** [comment]
Not finished yet
