### ISSUE TITLE
Change labels in budget line page

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#274]
https://madrid.gobierto.es/presupuestos/partidas/391-20/2015/economic/I

![captura de pantalla 2016-09-22 a las 16 20 52](https://cloud.githubusercontent.com/assets/24740/18751794/99c15088-80e0-11e6-8e68-a9b105c97e97.png)

In the 2nd box we put "Ingreso real", but more accurate would be "Ingreso presupuestado". And in the third one, we could 

1. unlink until we have the execution page for the specific budget line
2. include as the explanation the executed quantity

**Comment by ferblape** [comment]
My proposal 

![screen shot 2016-09-22 at 16 52 09](https://cloud.githubusercontent.com/assets/17616/18753197/ed51ad34-80e4-11e6-9ecd-f81802df3471.png)

- Ingreso presupuestado / habitante
- Ingreso presupuestado
- Ingreso real vs presupuestado
....

We'd need to reduce the font to .95em and make the explanation bigger.

**Comment by furilo** [comment]
+1

maybe we can maintain the font size and just put "pres." instead of presupuestado
