### ISSUE TITLE
Gobierto Data / Dataset: Data

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2744]
We'll start by building the base for the [Data tab of the dataset](https://www.figma.com/proto/IFqcY4iCKC9ukJkgfSRKEA/1910-Gobierto-Datos-Abiertos-Bocetos?node-id=18%3A684&viewport=974%2C5389%2C1&scaling=min-zoom). 

There are some things for which the API is not ready yet, or we have not defined how it works. In that cases, leave the element in place without interaction.

- **Sidebar**: We can ignore it all together for the time being, as it needs a refactor from Investments (just leave the space so when we have it, we just have to put it there and layout is not affected)
- **Dataset header**: Title, Favorite and Follow button (no API yet)
- **Tabs**: put them with placeholder or no destinations (styles for these tabs exists, but for the admin)
- **SQL Pad** (includes buttons and editor): 
  - Recent: inline modal with the list of recent queries.
  - Queries: queries component (to do in a further issue)
  - Save: when editing a query, triggers the editing flow (you can test it in Figma)
  - Execute: executes the query
- **Results**:
  - **Table**: 
  - **Visualization**: we'll leave contents of this tab for further issues.
  - **Download** button: the API will provide the list and URLs of formats available #2768

@entantoencuanto: update this issue with the link to the API Doc when available in Readme.io.

@jorgeatgu: any doubt with API usage post it here, so we can improve documentation. It's possible that the API needs further detail, we'll create issues when needed.

**Comment by ferblape** [comment]
Also, I think we should merge in master https://github.com/PopulateTools/gobierto/pull/2694
