### ISSUE TITLE
Gobierto Data API / List and URLs of formats available of a dataset

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2768]

**Comment by ferblape** [comment]
Related: https://github.com/PopulateTools/gobierto/issues/2773

**Comment by furilo** [comment]
I'm testing this in Burjassot

- File name: we should provide a useful file name: I propose: 
  - If no query is applied: slug-name.extension
  - If using saved query: slug-name_query-name.extension
  - If using non saved query: slug-name_query-YYMMDD-HHMMSS.extension
- JSON downloads CSV
- XLXS can't be opened: 
![image](https://user-images.githubusercontent.com/24740/73161969-04317b80-40ed-11ea-9e9c-836767b9ccd3.png)

**Comment by entantoencuanto** [comment]
For datasets the endpoints to download data in different formats use the dataset slug. To add the other file names to the API I think that the API should provide a download endpoint for each resource with a content-disposition attachment and filename as described in the issue.

The urls provided by the API meta of a dataset seems to work fine:

```json
"formats": {
                "json": "/api/v1/data/datasets/grupost-de-interes",
                "csv": "/api/v1/data/datasets/grupost-de-interes.csv",
                "xlsx": "/api/v1/data/datasets/grupost-de-interes.xlsx"
            },
```
cc/ @jorgeatgu
