### ISSUE TITLE
Gobierto Data / Keyboard Shortcuts (when in Dataset)

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2777]
Let's think on the keyboard shortcuts we want and keep track here: 

(bonus points for bilingual initial)

- [x] Execute query: **CMD+Enter**
- [x] Show Recents modal:  r (and be able to select a query with the keyboard up-down)
- [x] Show Queries modal: c
- [x] Show Results-Table: t
- [x] Show Results-Visualization: v
- [ ] ¿Undo (previous query): CMD+Z?

**Comment by jorgeatgu** [comment]
Maybe we should use the CTRL instead of CMD, thinking of users of other SO like Windows.

**Comment by furilo** [comment]
CMD for Mac, CTRL for the rest?

**Comment by furilo** [comment]
@Crashillo this has stopped working.
