### ISSUE TITLE
Gobierto Data / Weird behavior inserting % in query

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto#2779]
I'm trying to write the following query in https://burjassot.gobify.net/datasets > "Grups Interés GENCAT":

```sql
SELECT * FROM grupos_interes WHERE nom ilike '%wadus%' LIMIT 50;
```

1. When pressing shift + 5 to insert the %, the cursor goes to the beginning of the line and inserts a space
2. If copying the `%` in the clipboard and I try to paste it with right-click + paste, the same happens

**Comment by jorgeatgu** [comment]
Fixed. You can test in the next PR.
![replace 2020-01-22 14_43_24](https://user-images.githubusercontent.com/2649175/72899069-8f91c200-3d25-11ea-8b82-7de648135155.gif)
