### ISSUE TITLE
HTML element escaped in budgets comparator

### ISSUE THREAD

**Issue by rafadelascuevas** [PopulateTools/gobierto#282]
Element looks escaped `<a href="/presupuestos/partidas/33/2016/functional/G">Cultura</a>` under description of a specific budget item.
![tags escaped](https://www.dropbox.com/s/i7n04l2iqooo8hr/Captura%20de%20pantalla%202016-10-11%2017.17.32.png?raw=1)
This happens when you look up a specific item of the budget in detail. Example: [Arqueología y protección del Patrimonio Histórico-Artístico](https://presupuestos.gobierto.es/budget_lines/bijuesca/2016/336/G/functional)

**Comment by ferblape** [comment]
Fixed
