### ISSUE TITLE
Permalink for saved queries

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2823]
We should offer a permalink for saved queries in order to facilitate sharing. 

- [ ] When loading a saved query, update the address bar
- [ ] When hovering a link to a saved query I should be able to see the permalink and right-click to copy link

Proposed routes for saved queries/visualizations: 

- query: /datos/grupost-de-interes/q/ID
- vizz: /datos/grupost-de-interes/v/ID

Opinions @ferblape @entantoencuanto ?

**Comment by entantoencuanto** [comment]
I think it's OK. Behind the scenes, the paths to the resources would be /api/v1/data/queries/ID and /api/v1/data/visualizations/ID. Maybe we should add a validation to check that the query and visualization belongs to the dataset of the slug and redirect to the correct path if not.

**Comment by ferblape** [comment]
OK to me too. 

@entantoencuanto I'd ignore this for the moment.

**Comment by furilo** [comment]
OK all yours @jorgeatgu
