### ISSUE TITLE
Automate description custom field creation on module setup

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#2837]
When Gobierto data module is activated in a site we want to automatically add a custom field for the description of the datasets.

This can be implemented using a recipe from [Gobierto Seeds module](https://gobierto.readme.io/docs/developing-a-new-module-of-gobierto#section-seeds) that can be configured for the whole `GobiertoData` module.

**Comment by furilo** [comment]
I'd extend this issue to setup three basic custom fields: 

* Frecuency
* Category
* Description

This fields will be used by the front-end. I'd therefore try to apply some smart defaults: 

* We create those 3 fields on module activation (if they are not already created)
* We give them fixed names
* Front-end relies on those fixed names to
  * show the fields in the dataset page; if fields are not present they won't be used
  * build the sidebar

Following what we are doing in Investments, via module configuration we may be able to change those names or to extend the number of fields we show on the sidebar or dataset page. Therefore, in the conf we may have something like: 

```
gobierto_data_conf {
  sidebar {
    filters_to_show {
      datasets_category
      datasets_frecuency
    }
    dataset {
    filters_to_show {
      datasets_category
      datasets_frecuency
      datasets_description
    }
  }
}
```

This would be the default. 

(In investments we already have this conf, we should do something standard)

In the frontend, we would define a place to show the description, and then another one for the other custom fields, so we just show what fields are instructed by the configuration (or the defaults) in the corresponding order one beneath the other. 

cc @Crashillo @jorgeatgu

**Comment by entantoencuanto** [comment]
I'm going to create default vocabularies for frequency and category. Later an admin can manage their contents.

By default frequency vocabulary will have the terms (CA/EN/ES):
* Anual/Annual/Anual
* Trimestral/Quarterly/Trimestral
* Mensual/Monthly/Mensual
* Diària/Daily/Diaria

By default category vocabulary will have the terms (CA/EN/ES):
* General/General/General

**Comment by furilo** [comment]
I forgot: for categories there is an official list of terms (those to be
used in DCAT). So we can algo put those default values.

>

**Comment by furilo** [comment]
Ciencia y tecnología . . . . . . http://datos.gob.es/kos/sector-publico/sector/ciencia-tecnologia
Comercio . . . . . . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/comercio
Cultura y ocio . . . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/cultura-ocio
Demografía . . . . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/demografia
Deporte . . . . . . . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/deporte
Economía . . . . . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/economia
Educación . . . . . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/educacion
Empleo . . . . . . . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/empleo
Energía . . . . . . . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/energia
Hacienda . . . . . . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/hacienda
Industria . . . . . . . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/industria
Legislación y justicia . . . . . . http://datos.gob.es/kos/sector-publico/sector/legislacion-justicia
Medio ambiente . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/medio-ambiente
Medio Rural . . . . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/medio-rural-pesca
Salud . . . . . . . . . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/salud
Sector público . . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/sector-publico
Seguridad . . . . . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/seguridad
Sociedad y bienestar . . . . . . http://datos.gob.es/kos/sector-publico/sector/sociedad-bienestar
Transporte . . . . . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/transporte
Turismo . . . . . . . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/turismo
Urbanismo e infraestructuras. http://datos.gob.es/kos/sector-publico/sector/urbanismoinfraestructuras
Vivienda . . . . . . . . . . . . . . . . http://datos.gob.es/kos/sector-publico/sector/vivienda
