### ISSUE TITLE
HTML for the maps section

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#285]
- html in sandbox with the design you created
- put a placeholder carto map, and the controls (tree in the sidebar)
- create the local navigation we have for the gencat project
- go with the styles (colors) from the main fork, in a next to-do we will "localize" colors to the new layout

**Comment by martgnz** [comment]
This is being worked on on https://github.com/PopulateTools/gobierto-budgets-comparator/issues/2
