### ISSUE TITLE
Cache headers for API requests

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2854]
We should add headers to API requests so the client doesn't download things that haven't changed. 

We should provide 304 when the resource hasn't changed.

Also, see it using etags makes sense. 

https://thoughtbot.com/blog/introduction-to-conditional-http-caching-with-rails
https://thoughtbot.com/blog/take-control-of-your-http-caching-in-rails
https://medium.com/@jatescher/basic-rails-api-caching-7e5c57151bad

We should apply this to all API requests.

**Comment by ferblape** [comment]
@entantoencuanto we should investigate if the browser cache works or the request "touches" the server in this issue. Today in my tests with data module requests were being served by the browser, not the server. 

We'll plan this in the next days.
