### ISSUE TITLE
Add data_preview parameter to data query endpoint

### ISSUE THREAD

**Issue by entantoencuanto** [PopulateTools/gobierto#2879]
Add a `data_preview` parameter to query, dataset and queries show json endpoints, returning stats and query results limited to 50 rows if true. This must be the default behaviour if the param is not provided.

The front application should get the full results of a query from the csv format endpoint, much faster than the json serialization of results.

**Comment by ferblape** [comment]
@entantoencuanto if this one is completed, please close it.
