### ISSUE TITLE
Plans / CSV Import

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2885]
## Initial import

An admin will be able to import a CSV to an empty plan and have all data imported. 

* The plan will have to be already created; destination native vocabularies (categories, status) and custom fields must be already created and empty. 
* For the time being we ignore plugin custom fields 

Tasks: 

* [x] Add external_id native field to plan model
* [x] **A user will be able to download an empty CSV that will serve as a template**: Once that a plan has the native vocabularies and custom fields configured, the user can download an empty CSV with header names they will use as a template to import data. 
  - The external_id field will be included in the example
  - If the external_id is not null, it will be used
  - If the external_id is null, we'll create a secuential ID specific to this plan (as in Github Issues of a repo). This will allow us to to import the same plan in different contexts and maintain the external_id
  
## Update

* We base the process in the external_id
* If no external_id is provided we consider the project as a new one, and a secuential external_id is generated for this project
* We ignore deleted projects - if user wants to delete a project they should do it in the UI
* We ignore the position attribute - the one in the system will be kept
* When a project is matched, all their fields will be updated
  * Categories: we only take into account the last level (previous levels are ignored)
* The import works in two phases: 
  * Validation: We validate we can update/create all projects in the CSV: If there is a missmatch in some vocabulary field (we receive a term value that doesn't exist), or any other validation error, we provide feedback to the user and nothing is changed
  * Actual import

Tasks: 

- [x] A user will be able to export the current plan in CSV
- [x] Import preparation (validations)
- [x] Feedback to the user
- [x] Actual update

**Comment by entantoencuanto** [comment]
Can I merge this PR?

**Comment by furilo** [comment]
See https://github.com/PopulateTools/gobierto/pull/2889#issuecomment-604463601 - You decide if you want to tackle that in the PR or in a new one.

**Comment by entantoencuanto** [comment]
Yes, I think that this can be subject of another issue, but I'm going to check if it has a quick solution
