### ISSUE TITLE
Track activity log

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#29]
Every action that updates the database (creates, updates or destroys a record) must be tracked in the system.

These actions need to reflect:

- the action itself. I.e. `site.created` or `user.updated`
- the author of the action
- the subject of the action
- the receiver of the action, if applies
- the IP from which the author executed the action
- the timestamp

There are three kinds of actions:

1 - actions performed by regular users (citiziens) in the public or private site. I.e.: follow a budget line, vote for a comment, or update her personal data
2 - actions performed by an admin in a site, such as create a new participatory process
3 - actions performed by an admin not linked to a site, such as create a new admin, enable a site module, or disable a user account

The activity log will be displayed in different parts of the admin UI, not totally defined yet. For the moment:

- when visiting a user profile or admin profile, all the activity authored by the user will be displayed
- pending to define: 
  - where to view generic activity (3)

**Comment by ferblape** [comment]
Take a look @danguita. Tomorrow I'll start a branch and we can discuss about it on Friday morning

**Comment by furilo** [comment]
We have to start thinking how we'll handle actions like votes which must be
tracked but not related to any user

**Comment by ferblape** [comment]
I'm going to close this issue and create more specific ones.
