### ISSUE TITLE
Data / List visualizations of a dataset

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2905]
We'll do a list similar to this https://www.figma.com/proto/IFqcY4iCKC9ukJkgfSRKEA/1910-Gobierto-Datos-Abiertos-Bocetos?node-id=80%3A906&viewport=974%2C5389%2C1&scaling=min-zoom

@Crashillo  Is there a way we can have a static preview of the visualization? (generating all visualizations live maybe is too much?)

**Comment by Crashillo** [comment]
I was looking for exportation options in the perspective library, but unfortunately there isn't.

The library, when it's rendered, creates a worker. So N charts, N workers, plus our code. Actually, I don't know what performance will have this (let's try once in staging). Perhaps it would be easy to handle.

An alternative option, would be exporting an image, using an external library as html2canvas, in the time the visualization is saved. Then append this `canvas` to the visualization endpoint. But I don't think it's worth (I'm rejecting this option at the time I'm writing this comment)

I believe the library has two ways of render the component: the current one, who creates the worker, and the simple one, who just loads the data. Maybe we can do this when we're just listing the visualizations, and display the other one when we enter.

In any case, I'd starting render 10-20 visualizations at once to see how it works. And over 10 visualizations perhaps should be paginated as well, and we would take over only that number of displayed visualizations

**Comment by furilo** [comment]
OK, we'll try for the time being with showing the vizz as is.
