### ISSUE TITLE
Data / Show custom fields in dataset 

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2907]
![image](https://user-images.githubusercontent.com/24740/76429693-b37d9580-63af-11ea-8e04-0e3e99464023.png)

We should show default custom fields (Category & Frequency, and Description) in the dataset as per the Design https://www.figma.com/proto/IFqcY4iCKC9ukJkgfSRKEA/1910-Gobierto-Datos-Abiertos-Bocetos?node-id=71%3A0&viewport=974%2C5389%2C1&scaling=min-zoom

**Comment by ferblape** [comment]
Solved
