### ISSUE TITLE
Gobierto Mailing/Signup broken

### ISSUE THREAD

**Issue by Crashillo** [PopulateTools/gobierto#2912]
- [ ] Cannot create a new user as no mail is sent to you
- [ ] Resend a new confirmation mail is not working also 
- [ ] Reset the password seems to do nothing

**Comment by entantoencuanto** [comment]
https://rollbar.com/Populate/gobierto/items/1316/

**Comment by ferblape** [comment]
In which site? This is working to me in staging....

**Comment by furilo** [comment]
This was due to an issue with AWS that was fixed, and pending mails were sent. We forgot to close this.
