### ISSUE TITLE
Data / Dropdown modal below Perspective

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2970]
![image](https://user-images.githubusercontent.com/24740/79327554-f681da00-7f14-11ea-8db4-a2357f42b5fd.png)

The dropdown should appear on top of Perspective.

**Comment by furilo** [comment]
The scrollbar from Perspective keeps appearing: 

![image](https://user-images.githubusercontent.com/24740/79364069-16cb8c00-7f49-11ea-9fc7-5f5300506829.png)

**Comment by furilo** [comment]
![image](https://user-images.githubusercontent.com/24740/80108543-b4900e00-857c-11ea-8ac8-9e1325702dbc.png)

**Comment by ferblape** [comment]
Fixed in https://github.com/PopulateTools/gobierto/pull/3005
