### ISSUE TITLE
Plans / Header title is not being read from plan conf

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2978]
In the header table, where now appears "Projectes", it should read "Actuacions". It seems in that place is not reading it from the Plan conf. 

![image](https://user-images.githubusercontent.com/24740/79445008-41b2f000-7fdc-11ea-9355-f6403d3e4317.png)

**Comment by furilo** [comment]
Although it's JS, can you do this @entantoencuanto ?

**Comment by ferblape** [comment]
Solved
