### ISSUE TITLE
Plans / Include the SDG number before the SDG name

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#3002]
We showing the SDG name in https://diba-plan.gobify.net/planes/pla-de-mandat/2019/ods/1 we should include the SDG number (the external ID). 

So instead of: 

![image](https://user-images.githubusercontent.com/24740/79967185-ceebbe00-848e-11ea-9ef8-693f5f6976a0.png)

We would have to show "10. REDUCCIÓN DE LAS DESIGUALDADES"

Include it in #2935

**Comment by ferblape** [comment]
Fixed
