### ISSUE TITLE
Data / Avoid reload when click on main menu or submenu

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#3024]
If I'm inside a dataset, and click on the "Datos" in the main page menu, the Vue app gets reloaded. Is there some way to avoid this reload?

**Comment by jorgeatgu** [comment]
I can do it in the submenu but not in the top menu because it's from Rails.

**Comment by furilo** [comment]
Shouldn't we be able to know via JS which link is being clicked?
