### ISSUE TITLE
GobiertoPeople exports

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#303]
**Updated!**

Implement Gobierto export page. This is a cross-module page, that will enable  sections depending on the loaded modules in the site. It should live in `/open-data` URL.

The prototype is here: http://gobierto.dev/sandbox/download_open_data.html (the title is wrong, it should be Open Data).

For the moment just implement the exports for the GobiertoPeople module, which is:

- [ ] export people data (person_id, name, description, bio, content blocks...)
- [ ] export people events (person_id, person name, title, description, place, people invited...)
- [ ] export people statements (person_id, person name, year, person, content blocks...)
- [ ] export people posts -> just an RSS

For the moment we just need the CSV export, and the RSS for the blogs.

**Comment by furilo** [comment]
As agreed, we may just need for the moment : 

- [ ] export people data (person_id, name, description, bio, content blocks...)
- [ ] export people events (person_id, person name, title, description, place, people invited...)
- [ ] export people statements (person_id, person name, year, person, content blocks...)
- [ ] export people posts -> just an RSS?

**Comment by ferblape** [comment]
OK, let's implement just those things. The sandbox page is this one:

http://gobierto.dev/sandbox/download_open_data.html
