### ISSUE TITLE
Data / New fields for datasets: Source and License

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#3032]
![image](https://user-images.githubusercontent.com/24740/81167139-fd8c8d00-8f94-11ea-95c8-a9bc2972266c.png)

For the time being we can specify the License in the dataset text. 

In the future: 

* **Source**: We should allow to specify a source (name and URL) for a dataset. This can be a custom field. We should also think if we should detail the license associated to the sourced datasets. 

* **License**: A license will be a name and URL. Possible License for Getafe: https://opendefinition.org/od/2.1/es/

**Comment by stbnrivas** [comment]
I was thinking about wether this new fields should be a custom_field.  IMHO it won't be a custom_field because the same way that a person has a name. A dataset should have attributtes:
- source_name
- source_url
- source_license

it isn't needed to be a custom_field.

**Comment by furilo** [comment]
True. But we can reuse the system already in place to take advantage of features already applying to custom fields.

Another idea we have for the future are "recipes" that execute upon module creation and prepare the needed custom fields. For the time being let's proceed creating the custom fields. Thanks!

**Comment by stbnrivas** [comment]
ok, a question: it should source_* added to {all,single,specific} site(s)?

all => implemented as migration
single, specific => implemented as rake task || seed.rb

Thx

**Comment by stbnrivas** [comment]
ok, meanwhile I will implement the custom_field for source license.

I would like to ask if it is interesting to create a new type of custom field, to be able of build url and name into same custom_field

Thx

**Comment by furilo** [comment]
>
> I would like to ask if it is interesting to create a new type of custom
> field, to be able of build url and name into same custom_field
>

Feel free to open an issue to start the discussion.

**Comment by stbnrivas** [comment]
while I am adding the source license I thought it would sense:

1. If license should be like license name  or like an enum for example:
- Mit License
- Creative Commont
- ...

2. If license should be have a link url to full license rigths like this:

https://creativecommons.org/licenses/by-sa/4.0/

Thx

**Comment by furilo** [comment]
What I'd do is to use a Vocabulary for the Licences. In a first iteration
we can show the license title; in a second one we can put the URL in the
Description of the term, and have the field in this context use the
description as the href.

Also, we could reuse this vocabulary between sites (and we have an issue
pending for the future which is to have a set of vocabularies available to
create on any site - we are kind of doing this with the SDGs vocab, we
should improve the system in the future).

**Comment by stbnrivas** [comment]
I'd like to ask about which licenses names should be included as vocabulary for datasets. I am using below from now: 
- Open Data (ODbl)
- Open Data (ODC-By)
- Open Data (PDDL)

should include a link to its legal text? like https://opendatacommons.org/licenses/odbl/1-0/
should be translated or should use same name of license into english?

UPDATE:
I added  licenses types used into https://datos.gob.es

**Comment by furilo** [comment]
Open Data Commons Open Database License (ODbL)
Open Data Commons Attribution License
Open Data Commons Public Domain Dedication and License (PDDL)
Creative Commons Reconocimiento 4.0 Internacional (CC BY 4.0) https://creativecommons.org/licenses/by/4.0/

**Comment by furilo** [comment]
Regarding linking to the license, I said: 

https://github.com/PopulateTools/gobierto/issues/3032#issuecomment-820136824

> in a second one we can put the URL in the Description of the term, and have the field in this context use the description as the href.

Should we proceed with this?

**Comment by furilo** [comment]
@ferblape should we specify the URL in the Description, or is it too hacky?

**Comment by ferblape** [comment]
I'm not sure:

- it's a hack and will make the vue component very specific for this use-case. Or we could develop a specific component called DatasetLicense
- the other option I can envision is to have two separated fields: license name and license url. The problem is that an user can select a name and the incorrect url or viceversa.

I think the first one is my favourite option, yes

**Comment by furilo** [comment]
Or a DescriptionAsLink component?

**Comment by ferblape** [comment]
OK

@jorgeatgu @Crashillo can someone of you pick this and help @stbnrivas with the integration?
