### ISSUE TITLE
Contracts / Asignee page

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#3091]
Let's create a page for contract assignees, and link them to this page

For the moment include:

- name
- id
- list of contracts

Things to decide:

- identifier in the URL. Can we use the assignee ID (sometimes missing), or should we use a hash?

**Comment by furilo** [comment]
We could do something like https://www.figma.com/proto/gyMSROblmDqjkKt1TT8BcL5G/Gobierto-%2F-Contratos-Subvenciones?node-id=509%3A0&viewport=688%2C-1631%2C0.25&scaling=min-zoom
