### ISSUE TITLE
Plans / Autodetect slug & year in controller when plan URL is set to root

### ISSUE THREAD

**Issue by Crashillo** [PopulateTools/gobierto#3186]
When some plan defaults to root url, the ruby controller try to look for the slug, giving a view error, instead of autodetect it.

https://github.com/PopulateTools/gobierto/blob/29eb8c2e8afc201309b0a709f966e63bba42d1a9/app/controllers/gobierto_plans/plan_types_controller.rb#L66-L68

**Comment by entantoencuanto** [comment]
This error is no longer occurring, right? @Crashillo

**Comment by Crashillo** [comment]
Nope, it's working like a charm now :)
