### ISSUE TITLE
Gobierto / Activate AppSignal js errors

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#3240]
(and remove Rollbar)

**Comment by furilo** [comment]
Can we remove Rollbar, right? And also Mixpanel.

**Comment by ferblape** [comment]
Yes:

1. Activate Appsignal JS and check it works
2. Then remove Rollbar and Mixpanel js

**Comment by furilo** [comment]
AppSignal is already activated, right?

>

**Comment by ferblape** [comment]
no the js library

**Comment by ferblape** [comment]
@Crashillo now that you have access to Appsignal you can re-review this issue. The idea is to check if there's a way to get a sample of notifications, and if we can limit them to modern browsers.
