### ISSUE TITLE
Apply sites password protection to the API

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#3251]
When sites are password protected their API is still public. We should apply that authentication step also to the API, it's a http auth, so for api clients it's easy to implement and remove when the site becomes public.

**Comment by ferblape** [comment]
@entantoencuanto thoughts?

**Comment by entantoencuanto** [comment]
The user/password of http auth should be provided by the front generated by rails, like the authenticated user API token? The password to protect the site is not stored encrypted in the database, so it can be done.

If the environment is development the protection should be ignored as in current front

**Comment by ferblape** [comment]
It should use the user/password of the site, as we do for non api requests: https://github.com/PopulateTools/gobierto/blob/master/app/controllers/application_controller.rb#L38

**Comment by entantoencuanto** [comment]
Yes, I was talking about this user/password pair. My point is how the front component which is going to send requests to the API get these user/password pair to include in its requests

**Comment by ferblape** [comment]
Ah, yes, you are right, we should provide the credentials to the front api in a convenient way, maybe in the div that initializes the component:

```
        <div id="gobierto-datos-app"
             data-site-name="Ayuntamiento de Wadus"
             data-logo-url="https://..."
             data-home-url="https://...">
```
