### ISSUE TITLE
Review search box and suggestions styles

### ISSUE THREAD

**Issue by entantoencuanto** [PopulateTools/gobierto#3266]
Some styles should be fixed after using autocomplete for searches suggestions:
* Fix the colors on hover
* When the suggestions box is generated it takes the expanded width of the search box. After clicking out and in again the width of the suggestions doesn't take the correct width
![searches](https://user-images.githubusercontent.com/446459/88530729-1fc90080-d002-11ea-8a7b-28a971d09456.gif)
* Increase the width of the search box when when it widens after focus 

The changes can be included in PR #3237.

**Comment by ferblape** [comment]
@Crashillo did you move this card to Review in progress

**Comment by Crashillo** [comment]
Not guilty, your Honour!
