### ISSUE TITLE
Process to install successfully

### ISSUE THREAD

**Issue by flachica** [PopulateTools/gobierto#3320]
Hello, I have been reviewing the project and the [official documentation](https://gobierto.readme.io/docs/introduction) but I am still having problems to deploy the environment locally. Maybe I lack training in the stack on which the project is based (Ruby on rails, f.e.).

I don't know which installation guide to follow. I am having problems related to webpack and I am not very clear about the process of joining all the components of this project. Maybe I lack training in the stack on which the project is based.

If I follow [this](https://gobierto.readme.io/docs/server-installation-guide) guide I am not clear about the content that I have to put in the list of suggested folders

If I follow [this](https://gobierto.readme.io/docs/development-environment-1) guide it gives me a thousand problems of unsatisfied dependencies due to the configuration of my machine

The docker guide already announce that it is not the ideal alternative

I would appreciate any clues to mount the project

**Comment by ferblape** [comment]
Hi @flachica, we recommend you to follow the steps described in https://gobierto.readme.io/docs/development-environment-1 to install it successfully in a Mac environment with Homebrew. In case you have Linux you should be able to find equivalent packages using a package manager

**Comment by flachica** [comment]
The working environment I use is Linux. For this reason, some colleagues are working to facilitate the installation of the environment in [this](https://github.com/guadaltech/gobierto) repository. Any contribution is welcome. Thank you.

**Comment by juanjoselopezroldan** [comment]
Hello @flachica , I have been reviewing the project and in the official documentation is needs specify more information already that it's does not specified the errors more common for that many users can't continue use and need make new issue for every error that show in configuration or installation process.

We have been configuring a environment using docker and the file docker-composer.yaml have errors continuous and in the official documentation inticated  need init some times the container web, test and sidekid until that the init of entrypoint of images run correctly by that i have done modify the file Dockerfile customized with a entrypoint that to init the app gobierto with the less errors possible, also this image of docker have the packages versions update and recomended for official documentation by that the image used now in the docker-composer from repository has not indicate a updated image.

I hope it is useful to you the changes in the repository for to best the work of repository with docker services.

This changes in the repository was possible for the intervention of @Tedezed and  by me.

The link of repository with changes is this [LINK](https://github.com/guadaltech/gobierto) and alse we are send a pull request for that to apply of changes in your repository.

**Comment by Tedezed** [comment]
PR #3344
