### ISSUE TITLE
Calendar / Credentials decrypt error

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#3345]
It looks like Rails 6 migration broke the way that credentials are unencrypted to connect to remote calendars (at least Exchange and IBM Notes):

https://rollbar.com/Populate/gobierto/items/4274/
https://rollbar.com/Populate/gobierto/items/4273/

**Comment by entantoencuanto** [comment]
I've re-encrypted the credendials (and some other data in GobiertoParticipation::PollAnswer model using the same encryption mechanism) in production and staging and calendars update works again
