### ISSUE TITLE
Search method test coverage

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#3365]
@entantoencuanto I've just discovered that [this version of pg_search](https://github.com/PopulateTools/gobierto/pull/3361) introduces a bug in the search method, which is causing a 500 error in Gobierto: https://appsignal.com/populate/sites/5ebb88520264445dc7e68b5c/exceptions/incidents/244?timestamp=2020-09-22T13%3A07%3A10Z

But the tests are green, please review the coverage of the search methods and review why we couldn't detect this error in the test suite. Version 2.3.2 works fine.

And meanwhile, restore 2.3.2 version and freeze it

**Comment by entantoencuanto** [comment]
Hmm, there were a missing integration test. Added to PR, it fails with 2.3.3 version
