### ISSUE TITLE
Show horizontal scroll bar if there is scroll

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#3417]
When tables have horizontal scroll, we should show the scroll bar so we make it clear that there is hidden content. 

![image](https://user-images.githubusercontent.com/24740/96087189-c4e9cb80-0ec3-11eb-87f3-c550ec55a9a7.png)

**Comment by ferblape** [comment]
Closed in https://github.com/PopulateTools/gobierto/pull/3514
