### ISSUE TITLE
Dashboards API / dashboards_data

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#3453]
API structure defined here https://docs.google.com/document/d/1goWjuJI73qXMFjENe54-_V-AkYaQED7xAG9M5_ICE9o/edit

## GET /api/v1/dashboards_data?context=module::instance/ID&data_pipe=PIPE_TYPE

* parameters
  * context: module + instance type
  * data_pipe: a type of dashboard_data, for which we define a structure, and the needed transformations to fill this dashboard_data from the data inside the corresponding module. A data_pipe has a corresponding data structure and a widget type that will be used when building a dashboard

Examples of data_pipes

- **&data_pipe=project_metrics**
  * data structure (the one we are using for indicators): name, value, objective, date
  * widget template: metric (what we call "indicator" in the design, pending to be changed)
  * for the moment, we would fill this will all indicators across all projects from a given plan
  * (potential) we could store the progress of the plan, and the progress of each category. For this, on top of adding the project indicators, we would add the global progress, and the progress of each category. Examples: 
    * name, value, objective, date
    * Progreso del plan, 45%, 100%, [current date]
    * Progreso de Área de Acción Climática, 23%, 100%, [current date]
- **&data_pipe=budget_lines**: (this is just an example, we are not integrating it for the time being)
  * (pending)

## GET /api/v1/dashboards_data?context=module::instance/XX&data_pipe=project_metrics

- To populate the indicators tab in a Plan
- Example if context is GobiertoPlans::Plan/123, it would retrieve all indicators from across all plan projects

**Comment by ferblape** [comment]
I like the idea of data pipes and I have another example where it could be used: the data download section of a site (i.e https://pressupost.mataro.cat/descarga-datos) which is currently implemented with a custom query depending on the model and that fits totally with this idea of data pipe
