### ISSUE TITLE
Admin / Add an Indicator from a Project to a Dashboard

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#3459]
States: 

1. When hovering an indicator in the table, show a button "Add to a dashboard"
Visibihttps://www.figma.com/proto/qwGYAmtbMaeemrDfrHS0ky/1902_Gobierto_PAM?node-id=542%3A0&viewport=563%2C-739%2C0.125&scaling=min-zoom

2. A modal opens to select the Dashboard where to include the indicator
Visibihttps://www.figma.com/proto/qwGYAmtbMaeemrDfrHS0ky/1902_Gobierto_PAM?node-id=542%3A0&viewport=563%2C-739%2C0.125&scaling=min-zoom

- we'll only show Dashboard for which the current user has permissions
- we open the link "Do you need a new dashboard?" in a new window

3. When adding the indicator, we open the Dashboard page in a new window, with the new widget in Edit mode

https://www.figma.com/proto/qwGYAmtbMaeemrDfrHS0ky/1902_Gobierto_PAM?node-id=635%3A638&viewport=563%2C-739%2C0.125&scaling=min-zoom

**Comment by Crashillo** [comment]
Issue divided into:

- [x] https://github.com/PopulateTools/gobierto/issues/3613
- [x] https://github.com/PopulateTools/gobierto/issues/3614
- [x] https://github.com/PopulateTools/gobierto/issues/3615
