### ISSUE TITLE
Front / Show a Dashboard

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#3461]
We show the same Dashboard as in the back, minus the back parts, and embeded in the front layout

https://www.figma.com/proto/qwGYAmtbMaeemrDfrHS0ky/1902_Gobierto_PAM?node-id=541%3A294&viewport=563%2C-739%2C0.125&scaling=min-zoom

**Comment by Crashillo** [comment]
The viewer is already done in the sandbox. Once https://github.com/PopulateTools/gobierto/issues/3460 will be done, this visor will be included in plans also
