### ISSUE TITLE
Allow language options for admins

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#352]
For Sencelles we'd need to only show Catalan as available language. We could do a quick-fix hiding the language selector with CSS, but then even we'd need a way to specify a default language. So we'd at least need for the admin

- [ ] Choose default admin
- [ ] Choose available languages (for those available in the installation)

Thoughts @ferblape ?

**Comment by ferblape** [comment]
Agreed, I'd implement it as site setting.
