### ISSUE TITLE
Admin tools to control participation

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#354]
- [x] Allow an admin to check if an ID has already participated 
- [x] Allow an admin to delete the participation of an specific ID
- [x] Allow an admin to add a participation for a specific consultation, once she has checked the ID has not yet participated, or once she has deleted a previous participation 

(they want the offline participation to weight more than an online one)

I'll start with the markup

Any comment @ferblape ?

**Comment by ferblape** [comment]
Integrating this issue in #349
