### ISSUE TITLE
Vue table component

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#3596]
- Create/improve a Vue table component from what we have in Plans: 
  <img width="1158" alt="imagen" src="https://user-images.githubusercontent.com/24740/102972665-b4755300-44fb-11eb-9d0c-0cfb4b708f88.png">
  - Orderable columns, ASC DESC
  - Can select which columns to show with the right top link
  - Can specify the order of columns (is the same for the table and for the selector). This may be implied by the order of the columns provided to the component
  - Can specify defaults: visible columns, column which is ordered
  - The value of a column might be a link
  - Numeric fields should be right-aligned
- Implement component in Contracts (Home, Contracts tab)
- Implement component in Subvenciones

**Comment by Crashillo** [comment]
Sure, we only should set some default styles, but the functionality behind is already enclosed in a vue-mixin. Indeed, the precov2.org table is using such feature (sorting asc/desc, mainly)

**Comment by furilo** [comment]
Issue update, please review @Crashillo @ferblape

**Comment by furilo** [comment]
The idea is that @jorgeatgu take care of this.

**Comment by ferblape** [comment]
OK to me, I think that it would be great to invest a bit more and add tests to this component with https://testing-library.com/docs/vue-testing-library/intro/ because 

- in theory components are isolated, so they are easier to test
- if it's going to be used in three different places it gets more critical for the application

**Comment by Crashillo** [comment]
Looking forward to that vue-testing-library implementation 🥳

**Comment by jorgeatgu** [comment]
> Looking forward to that vue-testing-library implementation 🥳

First attempt
![Screenshot 2021-01-15 at 11 56 42](https://user-images.githubusercontent.com/2649175/104716984-f2dfe580-5728-11eb-9958-b389df9308f8.png)
