### ISSUE TITLE
Google Analytics code is not mandatory

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#36]
Site google analytics code shouldn't be a mandatory field.

**Comment by danguita** [comment]
It isn't mandatory, I can't reproduce a scenario in which it is required right now.

**Comment by ferblape** [comment]
Right, it was failing in my branch 29-..., not in master.

![screen shot 2016-11-10 at 20 18 37](https://cloud.githubusercontent.com/assets/17616/20190736/ec99a1de-a782-11e6-9567-6e48a70f7b84.png)

Sorry about that!

**Comment by danguita** [comment]
No probs mate! Thanks for reporting 👌
