### ISSUE TITLE
Consultations print version

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#360]
Sencelles is going to enable that people answer the consultation offline. Thus, we need a print version of the consultation for them to print. 

- We should do a print CSS
- It should contain the needed context info: start and end, basic instructions...
- It should fit in the less space possible, to avoid printing lots of pages

**Comment by furilo** [comment]
Hey @martgnz take a look at a printed output of the consultation in staging

http://sencelles.gobify.net/consultas_presupuestos/3/participa

**Comment by martgnz** [comment]
Sorry, the css was done before the desktop app was ready. Should be OK now.
