### ISSUE TITLE
Dashboard public URL

### ISSUE THREAD

**Issue by Crashillo** [PopulateTools/gobierto#3612]
There are a couple of places where the dashboard public url must be set.

1. Dashboards lists. Two links there: _view dashboard_ and _public view_
![imagen](https://user-images.githubusercontent.com/817526/104161489-3d90f300-53f3-11eb-9227-33912d486934.png)

2. Maker component. Top-right link: _view item_
![imagen](https://user-images.githubusercontent.com/817526/104161636-792bbd00-53f3-11eb-918b-58955231e3fd.png)

Since the 2nd one in built into a Vue component, the url has to be provided via `data-*` attributes

**Comment by entantoencuanto** [comment]
It's in https://github.com/PopulateTools/gobierto/pull/3623 and deployed in staging. The attribute is `data-preview-url`
