### ISSUE TITLE
Add trigger button to slickGrid table

### ISSUE THREAD

**Issue by Crashillo** [PopulateTools/gobierto#3613]
Add a button on hover to the current indicators table:

![imagen](https://user-images.githubusercontent.com/817526/104199050-400d4000-5427-11eb-8e9e-a9b6e4b58bad.png)

This button must display another modal with the serialized data from the selected row: name, value, objective, date

**Comment by ferblape** [comment]
Is this issue still pending?

**Comment by Crashillo** [comment]
Nope, dashboards stuff were merged, this issue seems to be unlinked to their PRs.

Closing
