### ISSUE TITLE
Contracts Vizz / Contract page iteration

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#3624]
An iteration over the contract page. We'll only show the "Adjudicatario" block, not the "Adjudicatarios"

If it's a minor contract (without tender) we shouldn't show the left column (Licitación, Presupuesto, Licitadores)

https://www.figma.com/proto/gyMSROblmDqjkKt1TT8BcL5G/Gobierto-%2F-Contratos-Subvenciones?node-id=1145%3A0&viewport=-630%2C-5948%2C0.5&scaling=min-zoom

**Comment by ferblape** [comment]
Sorry if the question is stupid, I don't understand how do you calculate the %. For example 9% of proceso abierto means that you have sum all open process contracts and get a total and this contract represents the 9% of that total?

**Comment by furilo** [comment]
Yes, the relative weight of this contract in the corresponding category (total by entity, by type, by process)
