### ISSUE TITLE
Need help running tests

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto#363]
Hello everyone!

First, congrats for Gobierto!! I really like the idea behind this project and the fact that it's been made open source. 🙂🙂

A couple of days ago I managed to setup the project for development without incidences. All tests passed and the application was accessible from the browser.

Now I'm trying to run the tests again but lots of them are failing and triggering a `SocketError: getaddrinfo: Name or service not known`. This is a piece of how it looks: 

![captura de pantalla 2017-02-18 a las 18 35 24](https://cloud.githubusercontent.com/assets/9287468/23095448/4431b884-f60a-11e6-89ce-4e0e8394561d.png)

(the whole `docker-compose run test` output is available at this [gist](https://gist.github.com/amiedes/a173bd73f920c6f8526191d299452817))

My two-day docker knowledge makes me suspect of something related to one of the needed containers not running properly, but that's all I can guess.

The fact that I had no problems the first time I ran the tests confuses me.

I'd really appreciate a lot if you could give me a hand with this 😅

Thanks in advance,

Alberto

**Comment by ferblape** [comment]
Hey @amiedes, thank you for your report. The problem is in Redis, it wasn't configured in the Docker compose file. I don't use Docker, so could you please test this PR and tell me if it works now?

https://github.com/PopulateTools/gobierto/pull/365

Thanks!

**Comment by amiedes** [comment]
Yes, it works! All green 🎉

Thanks a lot! 😄
