### ISSUE TITLE
Data / No LIMIT in default sql for big dataset

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#3635]
This https://github.com/PopulateTools/gobierto/issues/3370 is not working OK. In this dataset https://datos.gobierto.es/datos/contratos/resumen which is biiig, if you go to the Data tab, you get the default SELECT * FROM without limit

💥

![image](https://user-images.githubusercontent.com/24740/105094178-2d88ab80-5aa4-11eb-88bb-d68cb27918ac.png)

Why this dataset is not getting a LIMIT? 

Also, looking at this, I can't understand what this means:

![image](https://user-images.githubusercontent.com/24740/105094215-409b7b80-5aa4-11eb-946c-c7d49c9ad175.png)

Please propose other options.

**Comment by ferblape** [comment]
the limit has been fixed in contracts dataset but you need to remove your local storage, because the queries are stored to keep the history
