### ISSUE TITLE
Gobierto Data / Reduce the number of requests

### ISSUE THREAD

**Issue by Crashillo** [PopulateTools/gobierto#3658]
When we're requesting the queries or visualizations, currently two XHR are being done:
![imagen](https://user-images.githubusercontent.com/817526/105977594-d7160100-6091-11eb-8262-442967953d42.png)

The first one, is returning the public queries, and the latter the private ones. Since the app manages user tokens that approach is quite inefficient. Therefore:

1. API must check the `Authorization` token of the request. Cases:
    1.1 If none, it just returns the public items
    1.2 If token, it means the user is logged, return both public and private (their own) items
2. Front must refactor all the public/private stuff. In terms of XHR requests, it won't distinguish between public or private, it only make ONE call, once it fetches the results, it will seek the `relationships/user` properties to know which results are privates.

**Comment by entantoencuanto** [comment]
API part done in #3721, @Crashillo
