### ISSUE TITLE
Autocomplete site locations

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#38]
Site entity association will be available, for the moment, just for municipalities.

To get the list of municipalities we are going to use The Big Indexer municipalities collection.

The endpoint to obtain the suggestions is to a given query is `https://tbi.populate.tools/gobierto/collections/c-municipios-espanya/suggestions`.

It requires a parameter `query` and an authorization header:

- `query`: contains the query argument to the suggestions.
- `authorization: Bearer <TOKEN_BODY>`

(I'll provide the token body in private). Maybe it'll make sense to set that token as an installation setting, because I suspect we are going to use The Big Indexer in some places in the future.

In javascript you can do this:

```
var settings = {
  "crossDomain": true,
  "url": "https://tbi.populate.tools/gobierto/collections/c-municipios-espanya/suggestions",
  "method": "GET",
  "dataType": "json",
  "data": { "query": "foo"},
  "headers": {
    "authorization": "Bearer <TOKEN_BODY>"
  }
}

$.ajax(settings).done(function(response) {
  console.log(response);
});
```

The output of the endpoint is an object with a key `suggestions` and all the suggestions, composed of a value, and a raw data object:

```json
{
"suggestions": [
  {
    "value": "Abarán",
    "data": {
      "id": "30002",
      "name": "Abarán",
      "slug": "abaran",
      "municipality_id": 30002,
      "province_id": 30,
      "autonomous_region_id": 14
    }
  },
  {
    "value": "Abárzuza/Abartzuza",
    "data": {
      "id": "31002",
      "name": "Abárzuza/Abartzuza",
      "slug": "abarzuza-abartzuza",
      "municipality_id": 31002,
      "province_id": 31,
      "autonomous_region_id": 15
    }
  },
  {
    "value": "Abarca de Campos",
    "data": {
      "id": "34001",
      "name": "Abarca de Campos",
      "slug": "abarca-de-campos",
      "municipality_id": 34001,
      "province_id": 34,
      "autonomous_region_id": 7
    }
  }
]}
```

**Comment by ferblape** [comment]
Issue updated @danguita

**Comment by danguita** [comment]
Looking good, let's go for it 👍
