### ISSUE TITLE
Remove modules code citizien chars, participation, budgets consultations

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#3826]
Remove the following modules from the code:

- budgets consultations
- citizien chars
- participation

The steps would be:

- remove code in app/ and the subfolders
- remove tests
- remove affected javascript
- remove translations from config/locales
- update Readme documentation
- update config/application.yml 
- remove routes
- remove task
- update pg_search

Maybe it could be a good idea to split the task in three PRs, to simplify code review.

With the PR include a migration that disables any of these modules.

# staging 
backoffice:
- [ ] disable module and set new init_module 

test :
- [ ] test if rest of module keeps working after remove module

**Comment by stbnrivas** [comment]
mmm I am confused about this. remove or refactor it look like dependent

https://github.com/PopulateTools/gobierto/blob/91e9cfee11ab6bb55990e9ed38dae1a5612e6391/test/fixtures/gobierto_core/site_templates.yml#L1-L7

and its test:

```
bin/rails test test/models/gobierto_core/site_template_test.rb
```

**Comment by ferblape** [comment]
You can update the fixture and remove the poll and the partials:

```
markup: "<div class='gradient-bg'>My Template</div>" 
```

**Comment by ferblape** [comment]
This is almost done in https://github.com/PopulateTools/gobierto/pull/3909. I'm assigning @entantoencuanto, when you have some spare time you can finish this
