### ISSUE TITLE
Remove target _top from the bubbles visualization

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#3828]
Remove the target=_top so clicks on bubbles remain in the same window. 

![image](https://user-images.githubusercontent.com/24740/115242527-3d0aa580-a122-11eb-9dee-ad627c0e116d.png)

**Comment by Crashillo** [comment]
Remain at the active window, but opening a new one, right?

**Comment by furilo** [comment]
The issue is that a client has embeded the site in an iframe (inside
another site) and if you click on a bubble a new window is opened, loosing
the embed. So if we just remove the target everything will work as
expected.

(Do we need the target for anything?)
