### ISSUE TITLE
Indicators Module when we have a custom domain

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#393]
When we have a custom domain, like pressupostsoberts.sencelles.cat, calls to Populate Data fail: 

![captura de pantalla 2017-02-23 a las 16 55 39](https://cloud.githubusercontent.com/assets/24740/23266722/ebee497a-f9e8-11e6-8331-c4c9308bfcf6.png)

I guess its just because the domain is not authorized; and that by the moment we can do it manually. How should it be done @ferblape ?

**Comment by ferblape** [comment]
Populate Data API Token should be a configuration parameter of each site, so:

- [ ] Remove the environment variable `TBI_API_TOKEN`
- [ ] Create a new SiteConfiguration entry for the API token
- [ ] Search and replace in the code the references to `TBI_API_TOKEN`
