### ISSUE TITLE
Visualizations / Enable this module as the home page of a site

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#3935]
We need to be able to configure a visualization from Gobierto Visualizations module as the home page of a site.  This is a bit tricky and different to other modules, where a method is defined in the module definition:

```ruby
  def self.root_path(_)
    Rails.application.routes.url_helpers.gobierto_participation_root_path
  end
```

In this case the module consists on a set of visualizations defined in the JSON. I'd propose to set a new attribute (`home`: true`) in one of the visualizations to set that one as the visualization of the homepage. Something like:

```json
{
  "visualizations": {
    "costs": {
      "enabled": true,
      "home": true,
      "data_urls": {
        "costs": "https://...."
      }
    }
  }
}
```

@furilo if you agree with this solution I think it's not very difficult to implement /cc @entantoencuanto

**Comment by furilo** [comment]
Perfect
