### ISSUE TITLE
Remove node-sass

### ISSUE THREAD

**Issue by Crashillo** [PopulateTools/gobierto#3987]
Several compiling dependencies [have been deprecated](https://sass-lang.com/blog/libsass-is-deprecated) stucking another upgrades. For instance, [ruby 2.7.4](https://app.circleci.com/pipelines/github/PopulateTools/gobierto/4809/workflows/baf6dbcc-d746-42fd-9c7d-ffb7bef40a71/jobs/41820).

In addition, and possible related to, gobierto is no longer able to compile using `node v16` (which has became the LTS) due to this deprecation. Perhaps it will be necessary upgrade also `webpacker` (still `rc` though), as it has refactoring the _loaders_ configuration, which includes references to node-sass.

**Comment by furilo** [comment]
Removing webpacker would be an option? https://www.simplethread.com/rails-7-the-end-of-webpacker/ https://world.hey.com/dhh/rails-7-will-have-three-great-answers-to-javascript-in-2021-8d68191b

**Comment by ferblape** [comment]
Yeah, that's totally an option! I don't if that's a step too far on the path.

Maybe first we can migrate from node-sass to dart-sass which is the future, and with that we'll be closer to drop Webpacker. Removing webpacker will require to consider the different alternatives. I think the next step is to study https://github.com/rails/jsbundling-rails and understand if it allows us to migrate from Webpacker to esbuild without suffering too much.

**Comment by Crashillo** [comment]
Definitely it's an option, but as @ferblape said, it's too early. On one hand, rails 7 is yet freshly baked and on the other hand we need to pave the way before such breaking change. Step by step, the project must get rid of the outdated stuff, I'd try to migrate to webpacker 6 (because it's the most up-to-date milestone) and finally we'll dismiss webpacker once the previous steps are done.

**Comment by ferblape** [comment]
Hey, in the meantime is it possible to upgrade to node-sass 6? It supports the latest versions of node: https://github.com/rails/webpacker/pull/3217

**Comment by Crashillo** [comment]
I didn't have so much idea 'bout that, so I tested:
- gobierto hadn't a direct dependency to `node-sass`, it was through `@rails/webpacker`
- the release we're using (5.2.1) had node-sass, however, the latest (5.4.3) hadn't
- the link you pointed, it looks like works for webpacker 4.x branch. Gobierto implements 5.x branch
- I successfully run the app with node v16
- let's see if the tests are green and the deploy doesn't break anything.... 🤞

**Comment by jorgeatgu** [comment]
With the last upgrade to `@rails/webpack 5.4.3` the console throws some deprecation warnings from `dart sass`

```
Deprecation Warning: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(-$size, 2)
```

![Screenshot 2021-11-09 at 17 16 58](https://user-images.githubusercontent.com/2649175/140962276-4b9c41dc-2788-42a8-b799-35a371159eb2.png)

**Comment by Crashillo** [comment]
Sass offers [this migration tool](https://sass-lang.com/documentation/cli/migrator), to make the changes in an automatic way. BUT, I remember I've played already with it and some things gets broken.

I'll create an issue to update the semantics
