### ISSUE TITLE
Fix position on hover "info-box" on Tree-map

### ISSUE THREAD

**Issue by aramollis** [PopulateTools/gobierto#4015]
Related to how position is calculated to show info-box on hover on Tree-map visualization. See video-capture for details

https://user-images.githubusercontent.com/109797/143423855-93e394ec-5386-46e3-b25c-16a0dcf63e65.mp4

:

**Comment by Crashillo** [comment]
You may check this out [here](https://alcobendas.gobify.net/visualizaciones/contratos/)
