### ISSUE TITLE
Migrate from Google Analytics and Mixpanel to Ahoy

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#4032]
We are removing application  Google Analytics service and replacing it by Ahoy. If a customer setup its own analytics code, it'll be kept, meaning customers that don't set an Analytics code will have Ahoy stats.

Right now there are two analytics signatures installed:

- by default, the application installs the code defined in `config/application.yml`setting
- optional, the site has an attribute to set a specific code. We are keeping this code if has been set

## First part: remove Analytics

- [ ] remove the attribute from `config/application.yml` and update docs
- [ ] remove the app analytics JS from the templates. If the customer is using it's own code, keep it
- [ ] extra ball: remove references to Mixpanel

## Second part: add Ahoy track

- [ ] install ahoy gem
- [ ] track site visits, probably in an after filter
- [ ] track visits with a sidekiq job
- [ ] configure it to track site requests. Keep in mind the multitenancy, so you might wan to add the site host to the ahoy event

**Comment by furilo** [comment]
Some clients are using their own Analytics. Maybe if a custom Analytics ID has been set up from the admin, we should leave it?

**Comment by ferblape** [comment]
You are right, I'll reword the issue

**Comment by furilo** [comment]
We should activate this: https://github.com/ankane/ahoy#gdpr-compliance-1
