### ISSUE TITLE
Calendars / Start day at 7AM, not 00AM

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#4041]
When embedding an agenda in another site with not much height, this situation can happen (no events appear unless you scroll, because only night hours are visible and not much happens during this hours):

<img width="1247" alt="CleanShot 2022-02-04 at 09 14 58@2x" src="https://user-images.githubusercontent.com/24740/152494965-9d9d5a0a-1ebf-4732-9e77-1183a35acdd1.png">

https://www.alcobendas.org/es/persona/roberto-fraile-herrera

Let's configure the calendar so the day starts at 7AM

**Comment by jorgeatgu** [comment]
I've modified the start time, but it doesm't work because the calendar is inside a `div` with `display: none;`. When you change the day, then the calendar scroll to 7:00:00
![calendar-start-time](https://user-images.githubusercontent.com/2649175/153255324-6341786d-f6bc-4894-b7c3-7e72b1fd2153.gif)
.

**Comment by ferblape** [comment]
Weird, I don't understand why being loaded in a hidden div affects. Maybe there's a method in the API to reload the calendar once it has been loaded so it reloads at 7am?

**Comment by jorgeatgu** [comment]
Done.
![calendar-start-time](https://user-images.githubusercontent.com/2649175/153456043-db613cec-9a7d-44e2-ae09-f3ba60d8cf53.gif)
