### ISSUE TITLE
More verbose notice when signing up pre verification

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#405]

**Comment by furilo** [comment]
What do you think @ferblape ?

![captura de pantalla 2017-02-27 a las 12 55 57](https://cloud.githubusercontent.com/assets/24740/23360534/29ab566c-fcec-11e6-9533-2e6855d797cb.png)

**Comment by ferblape** [comment]
👍

**Comment by furilo** [comment]
Ok. Also, for the message once you have signedup a new email, I'd say:

"Genial. Revisa tu correo-e y haz click en el enlace de confirmación para poder continuar con el proceso de registro."

And the email can be: 


Subject: Confirma tu registro
```
Hola,

Para confirmar tu registro haz click en el siguiente enlace:

http://dival.gobify.net/user/confirmations/new?confirmation_token=NwozsggXHN2Hs14aAvptXkPR

(si no te estabas suscribiendo en SITE_NAME, puedes ignorar este mensaje)

Saludos

-- 
SITE_NAME · ENTITY_NAME
SITE_URL
```

**Comment by furilo** [comment]
(mail footer can be applied to all mails)
