### ISSUE TITLE
Consultations: Small alignment bug in desktop 

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#412]
![captura de pantalla 2017-02-27 a las 18 18 27](https://cloud.githubusercontent.com/assets/24740/23371702/44c82e48-fd19-11e6-86d2-2cca2ab5d123.png)

**Comment by martgnz** [comment]
I just increased the top offset in the latest PR but I couldn't see a misalignment similar to the one in the provided picture, even before (on Chrome, FF or Safari).

Could you look it up and report if now it's better?
