### ISSUE TITLE
Consultations: Flip status icons

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#415]
Right now we show a red down arrow when we propose reducing, and viceversa. Lets flip that: 

- show a red up arrow if we decide to augment
- show a down neutral (color main) arrow if we decide to reduce

 ![captura de pantalla 2017-02-27 a las 18 23 09](https://cloud.githubusercontent.com/assets/24740/23371867/cd8e9276-fd19-11e6-9214-c170f502ff6b.png)

**Comment by martgnz** [comment]
Addressed in #417.
