### ISSUE TITLE
Consultation app texts

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#451]
There are four texts pending to be defined:

1. [x] reduce text tooltip message
2. [x] a text describing what is deficit
3. [x] a text describing what is surplus
4. [x] a text describing what is being in balance

Once they have been defined we need to amend the app to change the message depending on the response status (deficit, surplus or balance).

**Comment by furilo** [comment]
## Non-reduceable

El gasto en algunas partidas no se puede reducir por compromisos adquiridos (contratos ya firmados, por ejemplo). En otros ejercicios si se podrá reducir. 

## Equilibrio

¡Estupendo! Con tus decisiones el presupuesto quedaría equilibrado: los ingresos del ayuntamiento serían iguales a los gastos, por lo que gastaríamos justo lo que tenemos y no generaríamos deuda. 

## Déficit

Con tus decisiones estaríamos gastando más de lo que ingresamos, por lo que estaríamos generando deuda. Esto no tiene por qué ser necesariamente un problema, siempre que sea una cantidad que vayamos a poder afrontar sin complicaciones. Pero si nuestro ayuntamiento ya tiene deuda, haríamos que esta creciese, y por tanto aumentaríamos lo que gastamos en pagar intereses. 

## Superavit

Con tus decisiones gastaríamos menos de lo que ingresamos en este ejercicio. Eso quiere decir que podríamos dedicar ese extra a pagar más deuda en caso que de tengamos, o a guardar recursos para años posteriores. Pero a lo mejor tiene sentido gastar todo lo que hemos recaudado, ¡piénsalo!
