### ISSUE TITLE
Fix aspect ratio in home page small avatars

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#537]
In GobiertoPeople module home page avatars have a fixed width and height of 30px. Remove the height attribute to fix the aspect ratio:

![screen shot 2017-03-21 at 11 29 21](https://cloud.githubusercontent.com/assets/17616/24143382/c7a4042e-0e29-11e7-81d5-63bdabf17371.png)

**Comment by furilo** [comment]
Should we implement this https://fengyuanchen.github.io/cropperjs/ so we can easily have squared avatars always? @ferblape
