### ISSUE TITLE
Globalize Gobierto Site HTML blocks (2/2)

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#547]
In the road to [Gobierto globalization](https://github.com/PopulateTools/gobierto/wiki/Globalization), we need to make Site HTML blocks dynamically link to pages.

We are going to add [Liquid](https://github.com/Shopify/liquid) to the three HTML blocks, so admins cuould use Liquid tags to refer to the CMS pages in a fancy way. For example, the following block:

```
The {{ page_link "privacy-page" }} page
```

When exists a `GobiertoCms::Page` with slug `privacy-page` and title `Privacy`, will result in:

```html
The <a href="/privacy-page">Privacy</a> page
```

**Comment by furilo** [comment]
Also, take into account that this is an initial step towards making some or all of the templates editable through the admin by any user.

**Comment by furilo** [comment]
should we have 

{{ page_name "privacy-page" }} => Privacy

and 

{{ page_url "privacy-page" }} => privacy-page

so we can do

```
<a href="{{ page_url "privacy-page" }}">{{ page_name "privacy-page" }}</a>
```

?

**Comment by ferblape** [comment]
Of course, I wanted the simplest version, but what you propose will make it more flexible without complicating the development very much.
