### ISSUE TITLE
Globalize Gobierto: UI changes in forms with globalized fields

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#549]
In the road to [Gobierto globalization](https://github.com/PopulateTools/gobierto/wiki/Globalization), we need to add support to multilanguage content in some models and modules, and admin forms need to change to support localization in different languages.

Define in the sandbox a sample form that shows a widget or control to switch from a locale to another.

**Comment by furilo** [comment]
Want to give it a shot @martgnz ?

**Comment by furilo** [comment]
Markup is ready. Assign the issue as needed, @ferblape
