### ISSUE TITLE
Site customization note about domains

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#606]
Right now this is hardcoded, right? 

![captura de pantalla 2017-04-05 a las 10 19 04](https://cloud.githubusercontent.com/assets/24740/24696357/81bcfb34-19e9-11e7-93cb-7ac14e35a08b.png)

Should we have an env var to specify the CNAME destination? In Dival's case, I understand it could be gobierto.go.dival.es ?

**Comment by amaia** [comment]
@furilo @ferblape it's defined in `config/application-yml` in `cname_record_target` , right now for dival it's set to `go.dival.es` but I'm going to change it to `gobierto.go.dival.es`

**Comment by ferblape** [comment]
This is already changed in Dival.
