### ISSUE TITLE
New Gobierto People module URLs

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#635]
Gobierto People URLs are a bit complex, and we are going to simplify them based on this document:

https://docs.google.com/spreadsheets/d/1TA2-fVTFzwcwjjdrMrzsuSBSgojrHsAV65zxKfnTTEE/edit#gid=0

A few comments:

- we'll keep the homepage of the module with the current URL
- we'll need to add a `slug` attribute to Person, PersonEvent and PersonStatement classes

**Comment by ferblape** [comment]
Username generation in Rails: https://alexcastano.com/generate-unique-usernames-for-ruby-on-rails/?utm_source=rubyweekly&utm_medium=email

**Comment by furilo** [comment]
Hey, it seems you have prepended "cargos-y-agendas" to all URLs. But the idea was to get rid of that too, right? https://docs.google.com/spreadsheets/d/1TA2-fVTFzwcwjjdrMrzsuSBSgojrHsAV65zxKfnTTEE/edit#gid=0

**Comment by amiedes** [comment]
I'll fix it 👍
