### ISSUE TITLE
Think about how GobiertoPeople events retrieval works

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto#666]
While working on issue #648  I’ve noticed several things we should start to think about:

Currently we have three places in the application that query for *person events*:

* GobiertoPeople welcome page
* GobiertoPeople agendas index
* GobiertoPeople person agenda

This means all the controllers related to this views make queries for events. It’s common for this views, that in addition of displaying the events, offer several filters: future and past events, filter by party, and when the calendar widget is present also show the events of that specific date.

This means that, in addition of duplicating the logic to query events between all the controllers, we are also duplicating a lot of integration tests that check this kind of filters are working correctly.

The use of the calendar widget in a view implies that several new integration tests are needed: one for the left and right month navigation arrows and another one for the date filter which is applied in the events summary when we click on a calendar date link.

Also, when the calendar widget is used in a view, the underlying controller must load a separate set of events, `@calendar_events`  in addition to the events requested for the events summary, usually `@events`.

Right now this calendar widget appears in two places: in the GobiertoPeople agendas welcome page and in the GobiertoPeople person agenda page. Maybe the next time we add the calendar widget somewhere we should think about extracting this component somehow so it can be tested in isolation.

Also when we click on a date link in the calendar, no matter in which controller we are (past events or future events) we have to display the events of that date (no matter if it’s a past date or future date). This leads to situations where a *past events controller* may load future events and vice versa. I find this kind of confusing.

I’m not for refactor right now, but I think we should start to keep track of this issues so when the time comes we have some information already written to help us make decisions.

I think it'd be nice to talk about this in the office.

**Comment by ferblape** [comment]
OK, let's talk in the office next week.
