### ISSUE TITLE
Hide admin settings when they are not relevant

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto#677]
While working on #627 I used javascript to hide the IBM Notes user and password fields when the calendar integration select is not set to "IBM Notes".

![image](https://cloud.githubusercontent.com/assets/9287468/25474711/711ab670-2b34-11e7-857d-38bab47e876f.png)

@furilo , do you think it'd be useful to also hide with JS everything related to calendar integration settings when the agendas submodule is not active? Should we also forbid in the server to perform any update on the calendar integration configuration when the agendas submodule is switched off?

**Comment by ferblape** [comment]
This can be closed after #1186
