### ISSUE TITLE
Solve IBM Notes "event duplication" problems

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto#678]
Even though the IBM Notes API we're using it's 9.0.1 version, some of the calendar endpoints we've been provided seem to be using an older version (8.something).

The JSON responses are almost identical, with the difference that in 8.x the received event IDs when making a call to `calendars GET` are not the unique ID of the event but a combination of it combined with a `_<revision_number>`.

As a result, we're importing as different events several "revisions" of the same event when the endpoint is on the 8.x version. It's easy to tell which endpoints are using the 8.x version because the IDs returned when performing `calendars GET` end up in `LotusReadRangeGenerated` instead of `LotusNotesGenerated`.

We should implemente a mechanism to avoid importing old revisions of this kind of events.

Useful documentation:

* [https://www-10.lotus.com/ldd/ddwiki.nsf/xpAPIViewer.xsp?lookupName=IBM+Domino+Access+Services+9.0.1#action=openDocument&content=catcontent&ct=api](https://www-10.lotus.com/ldd/ddwiki.nsf/xpAPIViewer.xsp?lookupName=IBM+Domino+Access+Services+9.0.1#action=openDocument&content=catcontent&ct=api)
* [http://www-01.ibm.com/support/docview.wss?uid=swg21969612](http://www-01.ibm.com/support/docview.wss?uid=swg21969612)

**Comment by furilo** [comment]
Should we just take into account that is a revision, and update the corresponding event accordingly?

**Comment by amiedes** [comment]
The documentation suggests to perform an API call to `calendar event GET` with the revision ID, and as a response we'll get the latest version of that event, with its "real ID".

We'll need to perform this API calls to `calendar event GET` for all the events returned by `calendar events GET` to retrieve information such as the event description and the attendees list, so I suggest that in the synchronization process, when we find one of this "revision events" we do nothing and just wait until the following call to `calendar events GET` gives us the "real information".

I'll be working on this today so I can validate this approach.

**Comment by amiedes** [comment]
This issue is becoming a bit more complicated. I've been working on trying to differentiate between recurrent events and duplicated events, which I think is relevant to this issue.

I'll share a few thoughts related to this topic just to keep track of this kind of information. I wrote them firstly in Spanish in my computer so I hope you don't mind not translating them:

## Observaciones para la versión **9.0.1**

* El `ID` sólo es único para los **eventos no recurrentes**. Eventos recurrentes comparten el mismo `ID` pero tienen un `recurrenceId` distinto. En este caso podría utilizarse como `ID` único una combinación del `ID` y el `recurrenceId`.
* **NOTA**: no todos los eventos devueltos por la aplicación son recurrentes.
* La información básica tanto de eventos recurrentes como no recurrentes puede sacarse sin problema de un `calendar events GET` (sin la sobrecarga de tener que hacer requests individuales).
* Cuando estamos ante un evento **no recurrente** el `calendar event GET` devuelve un único elemento. De aquí puede sacarse el event atendees, description, etc.
* Cuando estamos ante un evento **recurrente** el `calendar event GET` puede devolver uno o varios elementos. Si son todos idénticos (excepto por la fecha) se devolverá un único elemento. Si hay alguno que tiene personalizado algún campo (excepciones), se devolverá dentro del array de eventos. Dentro de la respuesta del `calendar event GET` hay un campo `links[:instances]` que contiene un endpoint (realmente es solo añadir `/instances` a la URL) que permite obtener todos los `recurrenceId` de todas las instancias de este evento. No obstante, como parece que la paginación no va muy fina, algunas de estas instancias no aparecen en `calendar events GET` sino que habría que pedirlas específicamente.

Tengo guardado algún ejemplo de este último punto, pero mejor no pegar el endpoint en GitHub.

Para la versión **9.0.1** propongo:

* Para los eventos **no recurrentes**, utilizar el ID como ID único. Como es único (de verdad), podría hacerse luego la petición a `calendar event GET`, que devolvería un único evento.
* Para los eventos **recurrentes** utilizar como ID único la combinación `ID/recurrenceId`, de este modo se puede hacer una petición luego a un `calendar event GET` para obtener información extra y funcionaría.
* En el caso de que un evento a priori no recurrente se convirtiese en recurrente, los nuevos eventos generados a efectos de la aplicación tendrían un nuevo ID (asumiendo que es ID + recurrenceId), así que se sincronizarían, y el ID del antiguo evento no recurrente dejaría de ser devuelto por la API sin venir acompañado a su vez de un `recurrenceId`, así que Gobierto lo marcaría como borrador (que es lo que queremos).
* Si seguimos este enfoque, lo ideal sería meter un *constraint unique* al `external_id` de `gp_person_events`.
* Cada uno de los elementos de la colección devuelta por `calendar events GET` tiene su propio campo `sequence`, que podría utilizarse para realizar peticiones a `calendar event GET` sólo cuando los datos hayan cambiado.

## Observaciones para la versión **8.5.x**

Tal y como se dice en [este doc](http://www-01.ibm.com/support/docview.wss?uid=swg21969612), los eventos que vienen de la versión 8.5.x carecen de los campos `recurrenceId` y `sequence`. Además, en esta versión los IDs sirven tanto para distinguir distintas instancias de un mismo evento recurrente como distintas revisiones de un evento que ha sido actualizado.

La API creo que sólo devuelve la última revisión, pero si no hacemos nada al respecto Gobierno irá almacenando todas las sucesivas revisiones del evento. Si se realiza una modificación de un evento recurrente, creo que se generan un nuevo ID para cada una de las repeticiones del evento. Es posible que este sea el motivo por el cual acabamos teniendo tantos eventos “repetidos” en el endpoint de esta version.

**¿Cómo solucionar esto?**

Cuando se hace una petición a `calendar event GET` con uno de los IDs de la versión 8.5.x, se devuelve el “equivalente” de la versión 9. En el resultado de esta llamada ya se puede obtener el ID real del evento, el `recurrenceId`, `sequence`, etc.

Propongo que para los endpoints que hacen uso de esta versión, la información que importemos provenga de las posteriores peticiones a `calendar event GET` en vez de a `calendar events GET`, de modo que el modo de operar sea cuasi-idéntico a como se hace en los endpoints de la 9.0.1

## Observaciones para ambas versiones

* Controlar los posibles errores al hacer peticiones a `calendar event GET`, es habitual que pete y devuelva una página HTML con una stacktrace de Java.
