### ISSUE TITLE
Limit the number of Sidekiq retries

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#684]
10 retries should be enough, and if possible, each one delayed from the other as Delayed Job does.

**Comment by bertocq** [comment]
I haven't found any way to specify a max number of retries globally, seems like it has to be specified on each worker `sidekiq_options` line (https://github.com/mperham/sidekiq/wiki/Error-Handling#configuration), although having a global variable to hold that number would be good idea to change it afterwards all at once.

About the delays between retries, it does them exponentially by default https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry

I've only found one job https://github.com/PopulateTools/gobierto/blob/9129855c0f81a705ac5c154dfd35e8e011abd069/app/jobs/user/verification_job.rb But I don't see the `include Sidekiq::Worker` on it, are you sure you're using Sidekiq on it? Maybe the inheritance from `ActiveJob::Base` does it and I'm doing a stupid question :)

**Comment by ferblape** [comment]
I think you are right @bertocq: there's no a global way to specify what I want. 

We use ActiveJob with Sidekiq as backend, that's why you don't find any Worker. And our main issue is with Algolia, which uses jobs to synchronize with the server in an asynchronous fashion.

**Comment by ferblape** [comment]
Discarded
