### ISSUE TITLE
Previsualization of draft elements

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#716]
Now, if you have an element published and update it to draft (pending), you are show the flash with "El evento ha sido actualizado. Ver el evento." But the link is a normal one, and as the item is not published, it gives a 404. Same happens if you create a new one. 

I'm testing this with events, confirmed with CMS pages. 

Didn't we have a preview link for draft elements, @ferblape? If we did, we should offer it in this preview links. If we didn't, we should have it.

**Comment by ferblape** [comment]
This issue should enable an admin to preview any of the following entities in draft:

- [ ] GobiertoCms::Page
- [ ] GobiertoPeople::Person
- [ ] GobiertoPeople::PersonEvent
- [ ] GobiertoPeople::PersonPost
- [ ] GobiertoPeople::PersonStatement
- [ ] GobiertoBudgetConsultations::Consultation
