### ISSUE TITLE
Content block records fixtures don't load on db:setup

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto#724]
Content block records fixtures (`test/fixtures/gobierto_common/content_block_records.yml`) are not being loaded during `bin/rails db:setup`, nevertheless they do load on `bin/rails db:fixtures:load`.

**Comment by ferblape** [comment]
Yes, that's on purpose. See: https://github.com/PopulateTools/gobierto/blob/master/db/seeds.rb#L1

Do you think they should be loaded?

**Comment by amiedes** [comment]
Is there any particular reason why they aren't being loaded? If not, I would add them.
