### ISSUE TITLE
Custom domain for attachments

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#733]
What would it take for attachments to have the domain of the site? So in http://dival.gobify.net/personas/jorge-rodriguez-gramage/biografia?locale=es that for this content block attachment: 

https://gobierto-populate-staging.s3-eu-west-1.amazonaws.com/site-4/gobierto_people/people/attachment-74e60db8-779a-4c5f-8585-7e46edb2fc59/170510-arranz01.jpg

the url would be instead something like:

https://**assets.dival.gobify.net**/site-4/gobierto_people/people/attachment-74e60db8-779a-4c5f-8585-7e46edb2fc59/170510-arranz01.jpg

Also:

- [ ] instead of site-4 the name of the site?
- [ ] the complicated directory structure is needed? We could get rid of gobierto_people at least?

----

Another case: 

- Normal attachment for a page: 

https://gobierto-populate-production.s3.eu-west-1.amazonaws.com/site-14/attachments/attachment-2608d5f6-5952-453d-836b-fe88609ef94f/0_9645_1.pdf

I'd convert it, at least, to

https://assets.gobierto.es/site-14/attachments/attachment-2608d5f6-5952-453d-836b-fe88609ef94f/0_9645_1.pdf

We should maintain the previous (actual) working, because it's already in production for Getafe.

**Comment by amiedes** [comment]
@amiedes -> Mirar el CNAME

**Comment by furilo** [comment]
Closing in favour of #1240
