### ISSUE TITLE
Participation admin HTML

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#752]
- [ ] Participation: Module configuration, groups lists
- [x] Group: 
  - [x] Meta
  - [x] Info
  - [x] Polls #833
  - [x] Contributions #786 
  - [x] Votings
  - [x] Agenda / pending #753 
  - [x] News / pending #754 
  - [x] Docs / pending #756

**Comment by ferblape** [comment]
We have just released this branch with all the Participation module features. I'll create a couple of small issues with the pending mockups from admin.
