### ISSUE TITLE
Gobierto Attachments global section in the admin

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#755]
We should have a global section in the admin for docs, and following the pattern, maybe for news and agendas. We could create a new block in the sidebar menu, something like: 

![captura de pantalla 2017-06-23 a las 15 22 58](https://user-images.githubusercontent.com/24740/27484009-dfd9aa42-5827-11e7-8ec2-ef440887b35a.png)

In those sections we would aggregate all the docs and references to where they have been uploaded. For the front we could mirror the structure. 

The docs section will be identical to the CMS section:

- Home: http://madrid.gobierto.dev/sandbox/admin_cms.html
- List of elements in a collection: http://madrid.gobierto.dev/sandbox/admin_cms_collection.html
- Edit attachment: http://madrid.gobierto.dev/sandbox/admin_cms_collection_page.html

**Comment by ferblape** [comment]
It makes sense to launch the same modal as we have now, but I'd add a feature: the ability to see to which attachings the attachment is attached to.
