### ISSUE TITLE
Idea pool page design

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#758]
### Literals

- [ ] We may use this for the Ask you mayor feature - we should think how are going to handle the literals. Per pool config? re https://github.com/PopulateTools/issues/issues/24

### Main page 

https://projects.invisionapp.com/d/main#/console/11320800/239644165/preview

- [x] We are going to allow for a description apart from the ideas request title, so maybe we can include the start of the description under the idea pool title, with an icon to expand it. 
- [x] Filters: I propose we stick with
1. Everything
2. Most valued
3. Least valued
4. Recent
5. Yours
- [x] Pager: big but mild buttons somewhere to go to the next-previous page. Probably we don't to convey the next-previous idea, just to load different content. 
- [x] Order button: I have a problem with this literal. We have two different types or orders: one is the chronological (which is the one most people its used to) and then the physical order on the canvas. As we are referring to this one, maybe we can think on another word for it? (I have tried, but don't come up with anything)
- [x] If a closing date (optional) is present, we should show some kind of countdown or warning. ie. Envía tus preguntas hasta el 25 de junio / Sólo te quedan 3 días para enviar tus preguntas!!

### Card onhover

- [x] Decide what are we finally doing on hover. We should reflect that you can click to expand the card to see description, comments; as well as allowing quick evaluation actions.

### Add idea

- [x] We have to decide what fields we are going to ask for. For sure: Title, description. Maybe leave extra or customizable fields for further iterations.

### Idea full view

- [x] It should show the title, description (and other fields) if they exists; evaluation tools; the comments thread.

**Comment by javierarce** [comment]
I'll start sharing some things design snippets here: 

This is the way I think we could show the closing date (in case we have one): 
![buttons](https://user-images.githubusercontent.com/4933/27646465-f3320de6-5c28-11e7-8e79-d3ebcbf5b843.png)

The idea is to show different texts as we approach the final date to instill a sense of urgency.

**Comment by furilo** [comment]
Great, we could even add a light yellow background to the text is the end
is very near.
