### ISSUE TITLE
Design homepage poll behaviour

### ISSUE THREAD

**Issue by martgnz** [PopulateTools/gobierto#803]
We need more designs about the homepage poll behaviour after selecting a response. Does it launch a modal? Is the result integrated into the widget?

**Comment by furilo** [comment]
What are you missing exactly?

**Comment by martgnz** [comment]
What happens after clicking on a poll response on the homepage? Do we need a send button in the widget to send the response? Or it sends the response automatically? After that, we probably need a small message with a share message and statistics about the poll?
