### ISSUE TITLE
Scopes CRUD (was Geographic admin zones)

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#812]
For Alcobendas, it has come up the need to categorize groups based on geography; in the future it would also be good to be able to localize specific ideas around the city, etc. We have to discuss and define how are we going to enable an admin to create the geo zones, and then similar to themes, enable those zones to be used to classify groups. 

## Enable an admin to create zones

We have several options: 

- enable flexible zone creation based on user drawing on a map
- try to import existing admin zones from other sources 
  - does INE have districts from towns? I think not, that districts are 
  - import shapefiles from municipal open data
- any other idea?

Each zone will have: 

- its geo 
- Name
- Description

Not for now but worth taking into account: the possibility of nested zones (municipality has districts, districts has neighborhoods).

We should take into account this will be used right not for Participation, but it will be used by other modules (ie. see projects from a budget or municipal plan associated with a neighborhood.

Geo zones would behave the same as Themes #782 

Also, we should let users select in which zone they live, and maybe in which zones they are interested in? Also for themes...

**Comment by furilo** [comment]
For the time being, we'll create a simple CRUD for general Scopes: Name, Description (optional)

This Scope will be used in the Process/Group configuration

In the future, we may add an option to a Scope to define a geozone

**Comment by amiedes** [comment]
Tasks:

- [x] Create `Scope` model, db table and fixtures.
- [x] Admin CRUD for scopes
- [x] Add delete link for issues in admin
- [x] Fix sortable handler for issues
- [x] Fix modal right padding for both issues and scopes
- [x] Integrate assign scope when creating process
- [x] Update process creation integration tests
- [x] Integrate process scope in process#show front
- [x] Create issue for fixing "destroy activities"

**(!!!)** For both scopes and issues, forbid deletion unless there are no items assigned to the corresponding issue/scope.
