### ISSUE TITLE
HTML for polls front and back

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#833]
## Admin

Polls list for a group: http://madrid.gobierto.dev/sandbox/admin_part_group_polls
Poll edit: http://madrid.gobierto.dev/sandbox/admin_part_group_polls_poll_edit

## Home 

http://madrid.gobierto.dev/sandbox/participation_group_polls

## Poll 

Launch from http://madrid.gobierto.dev/sandbox/participation_group_polls

Elements to integrate:

- Poll title
- Question title
- Question type:
  - I have added a control to select answer type (single or multiple) in <h4>Tipo de pregunta</h4>
  - If it's a single choice answer, if you select any option, the rest should be unchecked
  - If it's a multiple choice answer, you can check various options. Also, the div.help should be shown
- Question progress: 
  - I've skecthed a very basic JS to provide animation and button interaction, it should be properly integrated
- Progress map
  - move .active through li's as question advances
- Last screen: 
  - remove .poll_progress_map and .poll_actions

**Comment by amiedes** [comment]
## Order of tasks:

* [x] Sketch models and DB tables
* [x] Tests for admin polls index
* [x] Implement admin polls index
* [x] Write tests for `Poll`
* [x] Implement `Poll` create / update
* [x] Write tests for `PollQuestion`
* [ ] Implement `PollQuestion`
* [ ]  Write tests for `PollAnswerTemplate`
* [ ] Implement `PollAnswerTemplate`
* [x] Write tests for frontend
* [ ]  Implement frontend
