### ISSUE TITLE
Contributions tool public sections (first iteration)

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#843]
### List current process/group polls of contributions

Sandbox: http://madrid.gobierto.dev/sandbox/participation_group_contributions.html

### View a poll

Sandbox: http://madrid.gobierto.dev/sandbox/participation_group_contributions_container

In this iteration we should implement:

- list of ideas
- integrate buttons
- pagination
- display an idea debate
- vote an idea

For further iterations:

- add a new idea
- comment an idea
- vote an idea comment
- report an idea comment

**Comment by apradillap** [comment]
Depends on https://app.zenhub.com/workspace/o/populatetools/gobierto/issues/876
