### ISSUE TITLE
Define participation module public URLs

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#860]
- home: /participacion
- issues: /participacion /temas
- issue: /participacion/temas/cultura
- agendas: /participacion/agendas
- documents: /participacion/documentos
- news: /participacion/noticias
- processes: /participacion/procesos
  - process: /participacion/procesos/slug
  - info: /participacion/proceso/slug/informacion
  - polls: /participacion/proceso/slug/encuestas
  - poll: /participacion/proceso/slug/encuestas/slug
  - ideas: /participacion/proceso/slug/aportaciones
  - ideas pool: /participacion/proceso/slug/aportaciones/pool_slug
  - list of news: /participacion/proceso/slug/noticias
  - news: /participacion/proceso/slug/noticias/news_slug
  - list of docs: /participacion/proceso/slug/documentos
  - doc: /participacion/proceso/slug/documentos/doc_slug
  - agendas: /participacion/proceso/slug/agendas
  - event: /participacion/proceso/slug/agendas/event_slug
- groups: /participacion/groups
 - group: /participacion/group
 - (same as above for processes)

**Comment by ferblape** [comment]
@furilo please review and correct

**Comment by furilo** [comment]
Agendas, docs and news - they are global from the site, or specific to
participation?

Groups - in Spanish?

> --
http://twitter.com/furilo
http://www.furilo.com

**Comment by ferblape** [comment]
Sorry, I forgo to indent. Yes, all the links are for the participation module, so I have prepended a /participation segment

**Comment by furilo** [comment]
Great
-- 
http://twitter.com/furilo
http://www.furilo.com

**Comment by furilo** [comment]
Close if done @apradillap

**Comment by apradillap** [comment]
- processes: /participacion/procesos
  - info: /participacion/proceso/slug/informacion
  - polls: /participacion/proceso/slug/encuestas
  - poll: /participacion/proceso/slug/encuestas/slug
  - ideas: /participacion/proceso/slug/aportaciones
  - ideas pool: /participacion/proceso/slug/aportaciones/pool_slug
- groups: /participacion/groups
 - group: /participacion/group
 - (same as above for processes)

The routes of these resources are pending.

Groups are in the same controller as processes, @ferblape, do we duplicate it to have other routes and set them as /grupos/?

**Comment by furilo** [comment]
Processes: /participacion/procesos
Groups: /participacion/grupos

Specific process/group: /participacion/p/migrupo|miproceso/etc

**Comment by ferblape** [comment]
This one is already implemented, right?
