### ISSUE TITLE
Error creating a page/new in a process

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#895]
I can't create a page within a process, I always get this error:

![screen shot 2017-08-29 at 09 04 31](https://user-images.githubusercontent.com/17616/29808615-23916194-8c99-11e7-92e0-3d9659dc42fd.png)

Looks like the collection_id is not propagated through the PageForm.

**Comment by ferblape** [comment]
I can't reproduce this error anymore, which is weird. I'll let you review it, and if you can't reproduce it either we should close it.

**Comment by apradillap** [comment]
I think you solved it here.

https://github.com/PopulateTools/gobierto/commit/cc645ceab719632a2fa90a4efb5c5563f209171c#diff-a3af065412bc7c98381306ef46c000de

I close it.
