### ISSUE TITLE
Allow creating a site without specifying an entity

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#897]
Right now its compulsory that you define an entity to create a site. We should make this optional to allow the creation for sites that are not related with a place.

For modules that don't work without an entity (budget visualization, indicators) I'd show a warning in the admin if a site doesn't have entity and those modules are activated. 

cc @ferblape @apradillap

**Comment by apradillap** [comment]
👍  As low priority, we will implement it in the next sprints
