### ISSUE TITLE
Issues admin should not depend on Participation module

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#899]
I'm seeing in staging that Issues admin only appears if you have Participation module activated. Issues shall be used by other modules in the future, so I would not make this check. Issue admin should appear always, regardless of which module is activated. 

cc @apradillap

**Comment by apradillap** [comment]
👍  I modify it

**Comment by furilo** [comment]
This is not reflected yet on staging - is there something pending?

**Comment by furilo** [comment]
Sorry, I confused this with another thing.
