### ISSUE TITLE
You can't create the same Issue in two different sites

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#900]
Right now if you have an issue Sport, which a url "sport" in one site, you can't use that url for another issue in another site. You should be able to do that, since sites are totally independent. 

cc @apradillap

**Comment by apradillap** [comment]
Correct!! The validation is erroneous

```
validates :slug, uniqueness: :site_id
change by
validates :slug, uniqueness: { scope: :site }
```

I add it to the Sprint
