### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#904]
https://developers.google.com/speed/pagespeed/insights/?url=madrid.gobierto.es&tab=desktop

Should we apply some of the recommendations? We can start with the Blocking JS https://developers.google.com/speed/docs/insights/BlockingJS

cc @apradillap @ferblape

**Comment by apradillap** [comment]
I put it with low priority. This task is one of those I was reviewing lately for my petprojects.
