### ISSUE TITLE
Section editor for the admin

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#926]
Implement:

### List current site sections

Sandbox template: http://gobierto.dev/sandbox/admin_cms

![screen shot 2017-10-16 at 15 10 52](https://user-images.githubusercontent.com/17616/31613733-43cface8-b284-11e7-891b-17ba75982a84.png)

- List current site sections
- Count the number of items in the section
- The link to view the section will be broken for the moment

### New section

Mockup: http://gobierto.dev/sandbox/admin_cms_sections_section.html (click Configuration)

![screen shot 2017-10-16 at 15 12 37](https://user-images.githubusercontent.com/17616/31613797-818fabc8-b284-11e7-980f-45a251b3b8ab.png)

- Open the form in a modal
- Add localized fields fo the title/name of the section
- **Add a slug field** (it's missing in the mockup)
- Create the section should redirecto an emtpy show page (it wil be http://gobierto.dev/sandbox/admin_cms_sections_section)
- Track admin activity

**Comment by apradillap** [comment]
Deployed in:
- Staging + task
- Dival + task
- Production + task
