### ISSUE TITLE
Implement the Consultation reports interface

### ISSUE THREAD

**Issue by danguita** [PopulateTools/gobierto#96]
- [ ] Every Consultation should have a way to export its results in a portable format.
- [ ] Define that format, and implement an interface just to export the current Consultation responses anonymously.
- [ ] Think about providing some User (Participant) segmentation options.

**Comment by furilo** [comment]
Let's wait until we have designs for this (related with the visualization of the data).

**Comment by danguita** [comment]
Roger that! I'm moving it to a different milestone. Thanks.

**Comment by furilo** [comment]
Discussing design in #359

**Comment by ferblape** [comment]
Superseded by #359
