### ISSUE TITLE
Differentiate compulsory/optional fields in sandbox screens

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto#960]
- [ ] Review all fields that are required
- [ ] See if it makes sense to make the indication dynamic in some way?
- [ ] Add the corresponding indication ie. https://github.com/PopulateTools/gobierto/blob/5dffc0e4564e2cba8d2df9de7090b516822a44e7/app/views/gobierto_admin/gobierto_participation/processes/polls/_poll_question_modal.html.erb#L32

**Comment by furilo** [comment]
Please @Crashillo do a proposal as how we should do this.

**Comment by Crashillo** [comment]
An asterisk is the most common way but I wouldn't use here, I'd take advantage of the placeholder, instead.
![imagen](https://user-images.githubusercontent.com/817526/30915626-afb80046-a397-11e7-9d7f-53766d39010d.png)

**Comment by furilo** [comment]
We have code for doing this (look at the indication in the right): 

![captura de pantalla 2017-09-28 a las 10 55 22](https://user-images.githubusercontent.com/24740/30957794-8ae31086-a43b-11e7-9539-9e7a3eab9164.png)

Maybe we can add the "Required" over there? 

https://github.com/PopulateTools/gobierto/blob/4c243da59aeaf815d41c87b3c0f9bce8bf09b314/app/assets/stylesheets/comp-forms.scss#L41

(sorry I just remembered this)

**Comment by furilo** [comment]
So no extra code is needed, just adding the indication for required fields, with the label "Required" on top of the character limitation if needed. As in: 

https://github.com/PopulateTools/gobierto/blob/5dffc0e4564e2cba8d2df9de7090b516822a44e7/app/views/gobierto_admin/gobierto_participation/processes/polls/_poll_question_modal.html.erb#L32
