### ISSUE TITLE
Localize Admin UI

### ISSUE THREAD

**Issue by danguita** [PopulateTools/gobierto#99]
Since the latest features are pretty much stabilized, cover any missing translations within the `GobiertoAdmin` module's UI.

Also, consider enabling the `config.action_view.raise_on_missing_translations` setting to ensure everything is localized.

**Comment by ferblape** [comment]
Have you ever used https://github.com/glebm/i18n-tasks?

**Comment by danguita** [comment]
Yep, I was thinking of it when I wrote these lines 😛  I meant to enable the `raise_on_missing_translations` setting right after everything gets covered to early detect any new missing translations at run time, though using this tool as part of our CI process could be a good idea as well. Thanks for pointing it out!
