### ISSUE TITLE
In staging if I activate the agendas module when creating a person gives me 500

### ISSUE THREAD

**Issue by apradillap** [PopulateTools/gobierto#994]
In staging if I activate the agendas module when creating a person gives me 500

https://rollbar.com/Populate/gobierto/items/552/

Clue: validate slug with site scope

**Comment by apradillap** [comment]
@furilo I have verified that it is a global problem of several Gobierto resources: posts, people, etc. When creating these resources, simply check that if there is some resource at the site with the same slug and add a number. But when adding it to the database there is this restriction. Examples:

- Two persons with the same name in two different sites.
- Two person posts with the same title in two different sites.
- ...

`
t.index ["slug"], name: "index_gp_people_on_slug", unique: true
`

**Comment by ferblape** [comment]
Is this still an issue?
